//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/dom dojo/dom-construct dojo/dom-style dojo/keys jimu/BaseWidgetSetting jimu/dijit/Popup dijit/_WidgetsInTemplateMixin dijit/registry esri/request esri/arcgis/utils dijit/form/CheckBox dijit/form/ValidationTextBox dijit/form/Select dijit/form/Textarea".split(" "),function(q,m,w,f,k,e,x,r,y,t,b,u,z,n,v,h,p){return q([r,t],{baseClass:"jimu-widget-ISSpectralProfile-setting",ISLayers:[],bandNames:[],requestFlag:!0,startup:function(){this.inherited(arguments);
k.place('\x3cimg id\x3d"loadingSpectralProfile" style\x3d"position: absolute;top:0;bottom: 0;left: 0;right: 0;margin:auto;z-index:100;" src\x3d"'+require.toUrl("jimu")+'/images/loading.gif"\x3e',this.domNode);e.set("loadingSpectralProfile","display","none");this.populatePage();this.setConfig(this.config)},postCreate:function(){this.inherited(arguments);var a=0,b=0,c;for(c in this.map.layerIds)if("ArcGISImageServiceLayer"===this.map.getLayer(this.map.layerIds[c]).type||this.map.getLayer(this.map.layerIds[c]).serviceDataType&&
"esriImageService"===this.map.getLayer(this.map.layerIds[c]).serviceDataType.substr(0,16)){var l=this.map.getLayer(this.map.layerIds[c]).arcgisProps?this.map.getLayer(this.map.layerIds[c]).arcgisProps.title:"";if("_"!==l.charAt(l.length-1)){for(this.ISLayers[a]=this.map.getLayer(this.map.layerIds[c]);this.map.itemInfo.itemData.operationalLayers[b]&&this.map.itemInfo.itemData.operationalLayers[b].url!==this.ISLayers[a].url;)b++;this.map.itemInfo.itemData.operationalLayers[b]&&this.map.itemInfo.itemData.operationalLayers[b].title?
this.ISLayers[a].title=this.map.itemInfo.itemData.operationalLayers[b].title:this.map.getLayer(this.map.layerIds[c]).name?this.ISLayers[a].title=this.map.getLayer(this.map.layerIds[c]).name:this.map.getLayer(this.map.layerIds[c]).id?this.ISLayers[a].title=this.map.getLayer(this.map.layerIds[c]).id:this.ISLayers[a].title="Layer"+a;a++}}},setConfig:function(a){this.config=a;for(var d in this.ISLayers){var c=this.ISLayers[d].url.split("//")[1];if(a[c]){void 0!==a[c].hasNDVI&&b.byId("ndvi_"+d).set("checked",
a[c].hasNDVI);void 0!==a[c].hasOverlap&&b.byId("overlap_"+d).set("checked",a[c].hasOverlap);void 0!==a[c].bandCount&&b.byId("bandCount_"+d).set("value",a[c].bandCount);if(void 0!==a[c].bandNames){var l,e;for(e in a[c].bandNames)l=b.byId("bandNames_"+d).get("value")?b.byId("bandNames_"+d).get("value")+","+a[c].bandNames[e]:a[c].bandNames[e],b.byId("bandNames_"+d).set("value",l);b.byId("bandNames_"+d).set("value",a[c].bandNames)}void 0!==a[c].category&&b.byId("category_"+d).set("value",a[c].category);
void 0!==a[c].acquisitionDate&&b.byId("acquisitionDate_"+d).set("value",a[c].acquisitionDate);void 0!==a[c].nirIndex&&b.byId("nirIndex_"+d).set("value",a[c].nirIndex);void 0!==a[c].redIndex&&b.byId("redIndex_"+d).set("value",a[c].redIndex);void 0!==a[c].swirIndex&&b.byId("swirIndex_"+d).set("value",a[c].swirIndex)}}},getConfig:function(){for(var a in this.ISLayers){this.bandNames=b.byId("bandNames_"+a).get("value").split(",");var d={hasOverlap:b.byId("overlap_"+a).get("checked"),hasNDVI:b.byId("ndvi_"+
a).get("checked"),ndvi:b.byId("ndvi_"+a).get("checked"),ndmi:b.byId("ndvi_"+a).get("checked"),urban:b.byId("ndvi_"+a).get("checked"),yAxisLabel:b.byId("yAxisLabel_"+a).get("value")?b.byId("yAxisLabel_"+a).get("value"):"Data Values",bandCount:parseInt(b.byId("bandCount_"+a).get("value")),bandNames:this.bandNames,field:b.byId("acquisitionDate_"+a).get("value"),category:b.byId("category_"+a).get("value"),nirIndex:parseInt(b.byId("nirIndex_"+a).get("value")),redIndex:parseInt(b.byId("redIndex_"+a).get("value")),
swirIndex:parseInt(b.byId("swirIndex_"+a).get("value")),title:this.ISLayers[a].title};1===d.bandCount&&(d.hasNDVI=!1);""===b.byId("acquisitionDate_"+a).get("value")?(d.hasOverlap=!1,d.hasNDVI=!1):""===b.byId("nirIndex_"+a).get("value")?d.hasNDVI=!1:(""===b.byId("redIndex_"+a).get("value")&&(d.ndvi=!1,d.urban=!1),""===b.byId("swirIndex_"+a).get("value")&&(d.ndmi=!1,d.urban=!1));this.config[this.ISLayers[a].url.split("//")[1]]=d}return this.config},populatePage:function(){for(var a in this.ISLayers){var d=
k.create("tbody",{innerHTML:"\x3ctr\x3e\x3ctd\x3e"+this.ISLayers[a].title+'\x3c/td\x3e\x3c/tr\x3e\x3ctr\x3e\x3ctd class\x3d"first"\x3eTemporal Profile\x3cinput id\x3d"overlap_'+a+'"/\x3e\x3c/td\x3e\x3ctd class\x3d"first"\x3eIndex Profile\x3cinput id\x3d"ndvi_'+a+'"/\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr id\x3d"count_'+a+'"\x3e\x3ctd class\x3d"first"\x3e*Band Count\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3cinput id\x3d"bandCount_'+a+'"/\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr id\x3d"names_'+a+'" style\x3d"display:none;"\x3e\x3ctd class\x3d"first"\x3e*Band Names\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3ctextarea id\x3d"bandNames_'+
a+'"\x3e\x3c/textarea\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr\x3e\x3ctd class\x3d"first"\x3ey-axis Label: \x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3ctextarea id\x3d"yAxisLabel_'+a+'"\x3e\x3c/textarea\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr id\x3d"cat_'+a+'" style\x3d"display:none;"\x3e\x3ctd class\x3d"first"\x3eCategory\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3cselect id\x3d"category_'+a+'"\x3e\x3c/select\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr id\x3d"acqDate_'+a+'" style\x3d"display:none;"\x3e\x3ctd class\x3d"first"\x3e*Field\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3cselect id\x3d"acquisitionDate_'+
a+'"\x3e\x3c/select\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr id\x3d"nir_'+a+'" style\x3d"display:none;"\x3e\x3ctd class\x3d"first"\x3eNear-IR Band\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3cselect id\x3d"nirIndex_'+a+'"\x3e\x3c/select\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr id\x3d"red_'+a+'" style\x3d"display:none;"\x3e\x3ctd class\x3d"first"\x3eRed Band\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3cselect id\x3d"redIndex_'+a+'"\x3e\x3c/select\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr id\x3d"swir_'+a+'" style\x3d"display:none;"\x3e\x3ctd class\x3d"first"\x3eShortwave-IR Band\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3cselect id\x3d"swirIndex_'+
a+'"\x3e\x3c/select\x3e\x3c/td\x3e\x3c/tr\x3e'});k.place(d,f.byId("setting-table"));(new p({style:"margin:10px;"},"yAxisLabel_"+a)).startup();(new h({style:"margin:10px;"},"category_"+a)).startup();(new h({style:"margin:10px;"},"acquisitionDate_"+a)).startup();(new h({style:"margin:10px;",options:[{label:"No value",value:""}]},"nirIndex_"+a)).startup();(new h({style:"margin:10px;",options:[{label:"No value",value:""}]},"redIndex_"+a)).startup();(new h({style:"margin:10px;",options:[{label:"No value",
value:""}]},"swirIndex_"+a)).startup();(new n({style:"margin:10px;",onChange:function(a){a?(e.set(f.byId("acqDate_"+this.id.slice(-1)),"display","table-row"),e.set(f.byId("red_"+this.id.slice(-1)),"display","table-row"),e.set(f.byId("nir_"+this.id.slice(-1)),"display","table-row"),e.set(f.byId("swir_"+this.id.slice(-1)),"display","table-row")):(!1===b.byId("overlap_"+this.id.slice(-1)).get("value")&&e.set(f.byId("acqDate_"+this.id.slice(-1)),"display","none"),e.set(f.byId("red_"+this.id.slice(-1)),
"display","none"),e.set(f.byId("nir_"+this.id.slice(-1)),"display","none"),e.set(f.byId("swir_"+this.id.slice(-1)),"display","none"))}},"ndvi_"+a)).startup();(new n({style:"margin:10px;",onChange:function(a){a?e.set(f.byId("acqDate_"+this.id.slice(-1)),"display","table-row"):!1===b.byId("ndvi_"+this.id.slice(-1)).get("value")&&e.set(f.byId("acqDate_"+this.id.slice(-1)),"display","none")}},"overlap_"+a)).startup();(new v({required:!0,style:"margin:10px;"},"bandCount_"+a)).startup();(new p({required:!0,
title:"Enter names of all the bands separated by commas",style:"margin:10px;",onChange:function(a){b.byId("nirIndex_"+this.id.slice(-1)).removeOption(b.byId("nirIndex_"+this.id.slice(-1)).getOptions());b.byId("redIndex_"+this.id.slice(-1)).removeOption(b.byId("redIndex_"+this.id.slice(-1)).getOptions());b.byId("swirIndex_"+this.id.slice(-1)).removeOption(b.byId("swirIndex_"+this.id.slice(-1)).getOptions());b.byId("nirIndex_"+this.id.slice(-1)).addOption({label:"No value",value:""});b.byId("redIndex_"+
this.id.slice(-1)).addOption({label:"No value",value:""});b.byId("swirIndex_"+this.id.slice(-1)).addOption({label:"No value",value:""});var c=1,d="",e="",f="",h=new RegExp(/N[a-z]*I[a-z]*R[_]?[1]?/i),k=new RegExp(/red/i),m=new RegExp(/S[a-z]*W[a-z]*I[a-z]*R[_]?[1]?/i);if(a=a.split(","))for(var g in a)b.byId("nirIndex_"+this.id.slice(-1)).addOption({label:c+" ("+a[g]+")",value:g}),b.byId("redIndex_"+this.id.slice(-1)).addOption({label:c+" ("+a[g]+")",value:g}),b.byId("swirIndex_"+this.id.slice(-1)).addOption({label:c+
" ("+a[g]+")",value:g}),""===d&&h.test(a[g])&&(d=g),""===e&&k.test(a[g])&&(e=g),""===f&&m.test(a[g])&&(f=g),c++;b.byId("nirIndex_"+this.id.slice(-1)).set("value",d);b.byId("redIndex_"+this.id.slice(-1)).set("value",e);b.byId("swirIndex_"+this.id.slice(-1)).set("value",f)}},"bandNames_"+a)).startup()}this.setValues()},loopRequest:function(a){this.saveValue=a;e.set("loadingSpectralProfile","display","block");u({url:this.ISLayers[a].url+"/1/info/keyProperties",content:{f:"json"},handleAs:"json",callbackParamName:"callback"}).then(m.hitch(this,
function(a){if(a=a.BandProperties)for(var c=0;c<b.byId("bandCount_"+this.saveValue).get("value");c++){if(a[c]&&a[c].BandName)this.bandNames[c]=a[c].BandName;else{var d=c+1;this.bandNames[c]="Band_"+d.toString()}d=b.byId("bandNames_"+this.saveValue).get("value")?b.byId("bandNames_"+this.saveValue).get("value")+","+this.bandNames[c]:this.bandNames[c];b.byId("bandNames_"+this.saveValue).set("value",d)}else for(c=0;c<parseInt(b.byId("bandCount_"+this.saveValue).get("value"));c++)d=c+1,this.bandNames[c]=
"Band_"+d.toString(),d=b.byId("bandNames_"+this.saveValue).get("value")?b.byId("bandNames_"+this.saveValue).get("value")+","+this.bandNames[c]:this.bandNames[c],b.byId("bandNames_"+this.saveValue).set("value",d);e.set("loadingSpectralProfile","display","none");this.saveValue<this.ISLayers.length-1&&this.loopRequest(this.saveValue+1)}),m.hitch(this,function(){for(var a=0;a<parseInt(b.byId("bandCount_"+this.saveValue).get("value"));a++){this.bandNames[a]="Band_"+(a+1).toString();var c;c=b.byId("bandNames_"+
this.saveValue).get("value")?b.byId("bandNames_"+this.saveValue).get("value")+","+this.bandNames[a]:this.bandNames[a];b.byId("bandNames_"+this.saveValue).set("value",c)}e.set("loadingSpectralProfile","display","none");this.saveValue<this.ISLayers.length-1&&this.loopRequest(this.saveValue+1)}))},setValues:function(){for(var a=0;a<this.ISLayers.length;a++)this.ISLayers[a]&&this.ISLayers[a].bandCount&&(e.set(f.byId("count_"+a),"display","none"),e.set(f.byId("names_"+a),"display","table-row"),b.byId("bandCount_"+
a).set("value",this.ISLayers[a].bandCount),3>this.ISLayers[a].bandCount&&b.byId("ndvi_"+a).set("disabled",!0)),this._populateDropDown(b.byId("category_"+a),this.ISLayers[a].fields,"esriFieldTypeInteger",new RegExp(/Category/i)),this._populateDropDown(b.byId("acquisitionDate_"+a),this.ISLayers[a].fields,"esriFieldTypeDate",new RegExp(/acq[a-z]*[_]?Date/i)),1===b.byId("category_"+a).getOptions().length?(b.byId("ndvi_"+a).set("disabled",!0),b.byId("overlap_"+a).set("disabled",!0)):1===b.byId("acquisitionDate_"+
a).getOptions().length&&(b.byId("ndvi_"+a).set("disabled",!0),b.byId("overlap_"+a).set("disabled",!0));this.ISLayers.length&&this.loopRequest(0)},_populateDropDown:function(a,b,c,e){c=[{label:"Select a field",value:""}];var d=1,f="";if(b)for(var h in b){c[d]={label:b[h].name,value:b[h].name};var k=b[h].name;""===f&&e.test(k)&&(f=k);d++}a.addOption(c);a.set("value",f)}})});