//>>built
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/keys dojo/dom-style jimu/dijit/Popup ./Edit ../utils ./GroupSelector ../BasemapItem jimu/dijit/LoadingIndicator dijit/form/RadioButton".split(" "),function(n,p,q,d,b,e,h,f,k,l,r,m,t,g){return n([q,p],{baseClass:"jimu-widget-basemapgallery-setting",basemaps:[],mapItems:[],edit:null,editTr:null,popup:null,editIndex:null,spatialRef:null,postMixInProperties:function(){this.inherited(arguments);
d.mixin(this.nls,window.jimuNls.common);this.nomapTips=this.nls.basemapTips;this.nomapTips=this.nomapTips.replace("${import}","\x3cb\x3e"+this.nls.importBasemap+"\x3c/b\x3e");this.nomapTips=this.nomapTips.replace("${createNew}","\x3cb\x3e"+this.nls.createBasemap+"\x3c/b\x3e")},postCreate:function(){this.inherited(arguments);this.basemaps=[];this.mapItems=[];this.tipsSection.innerHTML=this.nomapTips;this.own(h(this.respectOnlineRaido,"click",d.hitch(this,function(){this.respectOnlineRaido.get("checked")&&
(b.setStyle(this.customBasemapSection,"display","none"),b.setStyle(this.tipsSection,"display","none"),b.addClass(this.baseMapsDiv,"mode-online"),this.clearBaseMapsDiv(),this.loadDefaultBasemaps())})));this.own(h(this.customRaido,"click",d.hitch(this,function(){this.customRaido.get("checked")&&(b.setStyle(this.customBasemapSection,"display","block"),b.setStyle(this.nomapTipsSection,"display","none"),b.removeClass(this.baseMapsDiv,"mode-online"),this.clearBaseMapsDiv(),this._createMapItems())})))},
startup:function(){this.inherited(arguments);this.map?(this.config.basemapGallery||(this.config.basemapGallery={}),this.setConfig(this.config)):k.set(this.baseMapsDiv,"display","none")},setConfig:function(a){this.config=a;this.basemaps=[];this.mapItems=[];e.forEach(a.basemapGallery.basemaps,function(a){this.basemaps.push({title:a.title,thumbnailUrl:a.thumbnailUrl,layers:a.layers,spatialReference:a.spatialReference})},this);2===a.basemapGallery.mode||!("mode"in a.basemapGallery)&&0<this.basemaps.length?
(this.customRaido.set("checked",!0),b.removeClass(this.baseMapsDiv,"mode-online"),k.set(this.customBasemapSection,"display","block"),this.clearBaseMapsDiv(),this._createMapItems()):(this.respectOnlineRaido.set("checked",!0),b.addClass(this.baseMapsDiv,"mode-online"),k.set(this.customBasemapSection,"display","none"),this.clearBaseMapsDiv(),this.loadDefaultBasemaps())},getConfig:function(){this.respectOnlineRaido.get("checked")?this.config.basemapGallery.mode=1:this.customRaido.get("checked")&&(this.config.basemapGallery.mode=
2);this.config.basemapGallery.basemaps=this.basemaps;return this.config},onAddBaseMapClick:function(){this._openEdit(null)},loadDefaultBasemaps:function(){this.loadingShelter.show();m._loadPortalBaseMaps(this.appConfig.portalUrl,this.map).then(d.hitch(this,function(a){a&&0!==a.length?(b.setStyle(this.nomapTipsSection,"display","none"),e.forEach(a,function(a){this._createMapItem(a,g.MODE_READONLY)},this)):b.setStyle(this.nomapTipsSection,"display","");this.loadingShelter.hide()}),d.hitch(this,function(a){console.warn(a);
this.loadingShelter.hide()}))},updateBasemap:function(a,c){var b=-1;e.some(this.basemaps,function(c,d){if(c.title===a)return b=d,!0});-1!==b&&(this.basemaps[b]=c,this.mapItems[b].updateItem(c))},addNewBasemap:function(a){this._createMapItem(a,g.MODE_EDIT);this.basemaps.push(a);b.setStyle(this.tipsSection,"display","none")},_createMapItems:function(){this.loadingShelter.show();0===this.basemaps.length?b.setStyle(this.tipsSection,"display",""):(b.setStyle(this.tipsSection,"display","none"),e.forEach(this.basemaps,
function(a){this._createMapItem(a,g.MODE_EDIT)},this));this.loadingShelter.hide()},_createMapItem:function(a,c){a=new g({appConfig:this.appConfig,basemap:a,folderUrl:this.folderUrl,nls:this.nls,spatialReference:this.map.spatialReference,mode:c});b.place(a.domNode,this.baseMapsDiv);c===g.MODE_EDIT&&(this.own(h(a,"delete",d.hitch(this,this._onMapItemDeleteClick))),this.own(h(a,"edit",d.hitch(this,this._onMapItemEditClick))));this.own(h(a,"selected",d.hitch(this,this._onMapItemSelectedChange)));this.mapItems.push(a)},
clearBaseMapsDiv:function(){e.forEach(this.mapItems,function(a){b.destroy(a.domNode)},this);this.mapItems=[]},_openEdit:function(a){a=a?a.basemap:null;var c=new r({nls:this.nls,folderUrl:this.folderUrl,appUrl:this.appUrl,basemap:a,basemaps:this.basemaps,map:this.map,token:m.getToken(this.appConfig.portalUrl)});this.popup=new l({titleLabel:a&&a.title||this.nls.createBasemap,autoHeight:!0,content:c,container:"main-page",width:800,height:600,buttons:[{label:this.nls.ok,key:f.ENTER,disable:!0,onClick:d.hitch(c,
c._onEditOk,this)},{label:this.nls.cancel,classNames:["jimu-btn-vacation"],key:f.ESCAPE,onClose:d.hitch(c,c._onEditClose,this)}]});c.startup()},_onMapItemEditClick:function(a){this._openEdit(a)},_onMapItemDeleteClick:function(a){this.basemaps=e.filter(this.basemaps,function(c){return a.basemap.title!==c.title},this);this.mapItems=e.filter(this.mapItems,function(c){return a!==c},this);b.destroy(a.domNode);0===this.mapItems.length&&b.setStyle(this.tipsSection,"display","")},_onMapItemSelectedChange:function(){e.some(this.mapItems,
function(a){return a.isSelected()},this)?b.setStyle(this.deleteBasemapBtn,"display","block"):b.setStyle(this.deleteBasemapBtn,"display","none")},_deleteSelectedItem:function(){var a=e.filter(this.mapItems,function(a){return a.isSelected()},this);this.mapItems=e.filter(this.mapItems,function(a){return!a.isSelected()},this);this.basemaps=e.map(this.mapItems,function(a){return a.basemap},this);e.forEach(a,function(a){b.destroy(a.domNode)},this);this._onMapItemSelectedChange()},onDeleteBaseMapBtnClick:function(){var a=
new l({width:400,height:200,titleLabel:this.nls.warningTitle,content:this.nls.confirmDelete,container:"main-page",buttons:[{label:this.nls.ok,key:f.ENTER,classNames:["map-selector-btn-ok"],onClick:d.hitch(this,function(){a.close();this._deleteSelectedItem()})},{label:this.nls.cancel,key:f.ESCAPE,classNames:["map-selector-btn-cancel","jimu-btn-vacation"],onClick:d.hitch(this,function(){a.close()})}]})},onChooseFromOnlineClick:function(){var a=new t({appConfig:this.appConfig,type:"HTML3D"===window.appInfo.appType?
"Web Scene":"Web Map",multiple:!0,folderUrl:this.folderUrl,nls:this.nls,map:this.map,spatialReference:this.map.spatialReference}),b=new l({width:700,height:500,titleLabel:this.nls.importTitle,content:a,container:"main-page",onClose:d.hitch(this,function(){try{a&&a.domNode&&a.destroy()}catch(u){console.error(u)}a=null;return!0}),buttons:[{label:this.nls.ok,key:f.ENTER,disable:!0,classNames:["map-selector-btn-ok"],onClick:d.hitch(this,function(){var c=a.getSelectedBasemaps();this._chooseMapFromWeb(c,
b)})},{label:this.nls.cancel,key:f.ESCAPE,classNames:["map-selector-btn-cancel","jimu-btn-vacation"],onClick:d.hitch(this,function(){b.close()})}]})},_chooseMapFromWeb:function(a,c){c.close();a&&0<a.length&&b.setStyle(this.tipsSection,"display","none");e.forEach(a,function(a){var b=e.map(this.basemaps,function(a){return a.title});a.title=m.getUniqueTitle(a.title,b);this._createMapItem(a,g.MODE_EDIT);this.basemaps.push(a)},this)}})});