//>>built
define("dojo/_base/declare jimu/BaseWidgetSetting dijit/_WidgetsInTemplateMixin dojo/_base/lang dojo/on dojo/Deferred dojo/dom-style dojo/dom-attr esri/request jimu/dijit/Message jimu/portalUtils jimu/portalUrlUtils jimu/utils dojo/store/Memory dijit/form/ValidationTextBox dijit/form/ComboBox jimu/dijit/CheckBox dijit/form/SimpleTextarea".split(" "),function(q,r,t,b,u,v,e,w,x,n,y,h,d,p){return q([r,t],{baseClass:"jimu-widget-print-setting",memoryFormat:new p,memoryLayout:new p,_portalPrintTaskURL:null,
validUrl:!0,startup:function(){this.inherited(arguments);this.setConfig(this.config);w.set(this.checkImg,"src",require.toUrl("jimu")+"/images/loading.gif");this.serviceURL.validator=b.hitch(this,this.validator);this.own(u(this.serviceURL,"Change",b.hitch(this,this.onUrlChange)))},validator:function(a){if(!this.validUrl)return this.serviceURL.invalidMessage=this.nls.urlNotAvailable,!1;var c=h.getNewPrintUrl(this.appConfig.portalUrl);if(a===c||/^https?:\/\/.+sharing\/tools\/newPrint$/.test(a)||/^https?:\/\/.+\/GPServer\//.test(a))return!0;
this.serviceURL.invalidMessage=this.nls.notPrintTask;return!1},onUrlChange:function(){this.validUrl=!0;if(this.serviceURL.validate()){var a=this.serviceURL.get("value");if(a){e.set(this.checkProcessDiv,"display","");this.memoryFormat.data={};this.memoryLayout.data={};this.defaultFormat.set("store",this.memoryFormat);this.defaultLayout.set("store",this.memoryLayout);this.defaultFormat.set("value","");this.defaultLayout.set("value","");e.set(this.defaultFormat.domNode.parentNode.parentNode,"display",
"none");e.set(this.defaultLayout.domNode.parentNode.parentNode,"display","none");var c=h.setHttpProtocol(this.serviceURL.get("value")),k=h.getNewPrintUrl(this.appConfig.portalUrl);c===k||/sharing\/tools\/newPrint$/.test(c)?e.set(this.checkProcessDiv,"display","none"):this._getPrintTaskInfo(a)}}},_getPrintTaskInfo:function(a){x({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback",timeout:6E4,load:b.hitch(this,this._handlePrintInfo),error:b.hitch(this,this._handleError)})},_handleError:function(){e.set(this.checkProcessDiv,
"display","none");this.validUrl=!1;this.serviceURL.validate()},_handlePrintInfo:function(a){e.set(this.checkProcessDiv,"display","none");e.set(this.defaultFormat.domNode.parentNode.parentNode,"display","");e.set(this.defaultLayout.domNode.parentNode.parentNode,"display","");var c=!1,k=!1;if(a&&a.parameters)for(var d=a.parameters.length,b=0;b<d;b++){var f=a.parameters[b];if("Format"===f.name||"Layout_Template"===f.name){for(var g=a.parameters[b].choiceList,h=g.length,m=[],l=0;l<h;l++)m.push({name:g[l],
id:g[l]});g=a.parameters[b].defaultValue;"Format"===f.name?(this.memoryFormat.data=m,this.defaultFormat.set("store",this.memoryFormat),this.config.serviceURL===this.serviceURL.get("value")&&this.config.defaultFormat?this.defaultFormat.set("value",this.config.defaultFormat):this.defaultFormat.set("value",g)):(this.memoryLayout.data=m,this.defaultLayout.set("store",this.memoryLayout),this.config.serviceURL===this.serviceURL.get("value")&&this.config.defaultLayout?this.defaultLayout.set("value",this.config.defaultLayout):
this.defaultLayout.set("value",g))}"string"===typeof f.name&&"web_map_as_json"===f.name.toLowerCase()&&(c=!0);"string"===typeof f.name&&"output_file"===f.name.toLowerCase()&&(k=!0)}c&&k||(this.validUrl=!1,this.serviceURL.validate())},setConfig:function(a){this.config=a;this.loadPrintURL(a);a.defaultTitle?this.defaultTitle.set("value",d.stripHTML(a.defaultTitle)):this.defaultTitle.set("value","ArcGIS WebMap");a.defaultAuthor?this.defaultAuthor.set("value",d.stripHTML(a.defaultAuthor)):this.defaultTitle.set("value",
"Web AppBuilder for ArcGIS");a.defaultCopyright&&this.defaultCopyright.set("value",d.stripHTML(a.defaultCopyright));this.copyrightEditableChk.setValue(!1!==a.copyrightEditable)},_onTitleBlur:function(){this.defaultTitle.set("value",d.stripHTML(this.defaultTitle.get("value")))},_onAuthorBlur:function(){this.defaultAuthor.set("value",d.stripHTML(this.defaultAuthor.get("value")))},_onCopyrightBlur:function(){this.defaultCopyright.set("value",d.stripHTML(this.defaultCopyright.get("value")))},getConfig:function(){if(!this.serviceURL.validate()){var a=
new n({message:this.nls.warning,buttons:[{label:this.nls.ok,onClick:b.hitch(this,function(){a.close()})}]});return!1}this.config.serviceURL=this.serviceURL.get("value");this.config.defaultTitle=d.stripHTML(this.defaultTitle.get("value"));this.config.defaultAuthor=d.stripHTML(this.defaultAuthor.get("value"));this.config.defaultCopyright=d.stripHTML(this.defaultCopyright.get("value"));this.config.defaultFormat=this.defaultFormat.get("value");this.config.defaultLayout=this.defaultLayout.get("value");
this.config.copyrightEditable=this.copyrightEditableChk.getValue();return this.config},loadPrintURL:function(){this._getPrintTaskURL(this.appConfig.portalUrl).then(b.hitch(this,function(a){this.serviceURL.set("value",a)}))},_getPrintTaskURL:function(a){var c=new v;if(this.config&&this.config.serviceURL)return c.resolve(this.config.serviceURL),c;y.getPortalSelfInfo(a).then(b.hitch(this,function(a){(a=a&&a.helperServices&&a.helperServices.printTask&&a.helperServices.printTask.url)?c.resolve(a):c.reject("error")}),
b.hitch(this,function(a){new n({message:this.nls.portalConnectionError||a&&a.message||"portal connection error"});c.reject("error");console.error(a)}));return c}})});