//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/html dojo/_base/lang dojo/query dojo/on dojo/when esri/lang dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/LayerInfos/LayerInfos ../utils jimu/utils ./QuerySourceSetting ./LocatorSourceSetting jimu/dijit/CheckBox jimu/dijit/SimpleTable jimu/dijit/LoadingIndicator".split(" "),function(q,l,m,d,h,e,r,t,u,v,w,f,k,n,p,x,y){return q([v,u],{baseClass:"jimu-widget-search-setting",_currentSourceSetting:null,_defaultZoomScale:null,postCreate:function(){this.inherited(arguments);
this.sourceList=new y({autoHeight:!1,selectable:!0,fields:[{name:"name",title:this.nls.name,width:"auto",type:"text",editable:!1},{name:"actions",title:"",width:"70px",type:"actions",actions:["up","down","delete"]}]},this.sourceList);m.setStyle(this.sourceList.domNode,"height","100%");this.sourceList.startup();this.own(e(this.sourceList,"row-select",d.hitch(this,this._onSourceItemSelected)));this.own(e(this.sourceList,"row-delete",d.hitch(this,this._onSourceItemRemoved)));this.own(e(this.sourceList,
"row-add",d.hitch(this,this._checkConfig)));this.showInfoWindowOnSelect=new x({checked:!0,label:this.nls.showInfoWindowOnSelect2},this.showInfoWindowOnSelect)},startup:function(){this.inherited(arguments);this.config&&this.config.sources||(this.config.sources=[]);this.shelter.show();w.getInstance(this.map,this.map.itemInfo).then(d.hitch(this,function(a){this.layerInfosObj=a;f.setMap(this.map);f.setLayerInfosObj(this.layerInfosObj);f.setAppConfig(this.appConfig);r(f.getConfigInfo(this.config)).then(d.hitch(this,
function(a){this.domNode&&(this.setConfig(a),this.shelter.hide())}))}))},setConfig:function(a){this.config=a;a=a.sources;this.allPlaceholder.set("value",k.stripHTML(this.config.allPlaceholder));this.showInfoWindowOnSelect.setValue(t.isDefined(this.config.showInfoWindowOnSelect)?!!this.config.showInfoWindowOnSelect:!0);l.forEach(a,d.hitch(this,function(a,b){var g=this.sourceList.addRow({name:a.name||""});g&&g.success?(this._setRelatedConfig(g.tr,a),0===b&&setTimeout(d.hitch(this,function(){this.sourceList.selectRow(g.tr)}),
100)):console.error("add row failed ",g)}))},getConfig:function(){this._currentSourceSetting&&this._closeSourceSetting();var a={allPlaceholder:k.stripHTML(this.allPlaceholder.get("value")),showInfoWindowOnSelect:this.showInfoWindowOnSelect.checked},c=this.sourceList.getRows(),b=[];l.forEach(c,d.hitch(this,function(a){var c=this._getRelatedConfig(a);delete c._definition;this._removeRelatedConfig(a);b.push(c)}));a.sources=b;return a},destroy:function(){f.setMap(null);f.setLayerInfosObj(null);f.setAppConfig(null);
this.inherited(arguments)},_onAllPlaceholderBlur:function(){this.allPlaceholder.set("value",k.stripHTML(this.allPlaceholder.get("value")))},_onMenuItemClick:function(a){this._currentSourceSetting&&!this._currentSourceSetting.isValidConfig()?this._currentSourceSetting.showValidationTip():(a=a&&a.target&&m.getAttr(a.target,"type"),"locator"===a?this._addNewLocator():"query"===a&&this._addNewQuerySource())},_addNewLocator:function(){this._createNewLocatorSourceSettingFromMenuItem({},{})},_addNewQuerySource:function(){this._createNewQuerySourceSettingFromMenuItem({},
{})},_setRelatedConfig:function(a,c){h(a).data("config",d.clone(c))},_getRelatedConfig:function(a){return h(a).data("config")[0]},_removeRelatedConfig:function(a){return h(a).removeData("config")},_createNewLocatorSourceSettingFromMenuItem:function(a,c){var b=new p({nls:this.nls,map:this.map});b.setDefinition(c);b.setConfig({url:a.url||"",name:a.name||"",singleLineFieldName:a.singleLineFieldName||"",placeholder:a.placeholder||"",countryCode:a.countryCode||"",panToScale:a.panToScale||!1,zoomScale:a.zoomScale||
this._defaultZoomScale,maxSuggestions:null===a.maxSuggestions||void 0===a.maxSuggestions?6:a.maxSuggestions,maxResults:a.maxResults||6,searchInCurrentMapExtent:!!a.searchInCurrentMapExtent,type:"locator"});b._openLocatorChooser();b.own(e(b,"select-locator-url-ok",d.hitch(this,function(a){(a=this.sourceList.addRow({name:a.name||"New Geocoder"},this.sourceList.getRows().length))&&a.success&&(this._currentSourceSetting&&this._closeSourceSetting(),b.setRelatedTr(a.tr),b.placeAt(this.sourceSettingNode),
this.sourceList.selectRow(a.tr),this._currentSourceSetting=b)})));b.own(e(b,"reselect-locator-url-ok",d.hitch(this,function(a){var b=this._currentSourceSetting.getRelatedTr();this.sourceList.editRow(b,{name:a.name})})));b.own(e(b,"select-locator-url-cancel",d.hitch(this,function(){this._currentSourceSetting!==b&&(b.destroy(),b=null)})))},_createNewLocatorSourceSettingFromSourceList:function(a,c,b){this._currentSourceSetting&&this._closeSourceSetting();this._currentSourceSetting=new p({nls:this.nls,
map:this.map});this._currentSourceSetting.setDefinition(c);this._currentSourceSetting.setConfig({url:a.url||"",name:a.name||"",singleLineFieldName:a.singleLineFieldName||"",placeholder:a.placeholder||"",countryCode:a.countryCode||"",panToScale:a.panToScale||!1,zoomScale:a.zoomScale||this._defaultZoomScale,maxSuggestions:null===a.maxSuggestions||void 0===a.maxSuggestions?6:a.maxSuggestions,maxResults:a.maxResults||6,searchInCurrentMapExtent:!!a.searchInCurrentMapExtent,enableLocalSearch:!!a.enableLocalSearch,
localSearchMinScale:a.localSearchMinScale,localSearchDistance:a.localSearchDistance,radiusUnit:a.radiusUnit,type:"locator"});this._currentSourceSetting.setRelatedTr(b);this._currentSourceSetting.placeAt(this.sourceSettingNode);this._currentSourceSetting._processlocalSearchTable(!!a.enableLocalSearch);this._currentSourceSetting.own(e(this._currentSourceSetting,"reselect-locator-url-ok",d.hitch(this,function(a){var b=this._currentSourceSetting.getRelatedTr();this.sourceList.editRow(b,{name:a.name})})))},
_closeSourceSetting:function(){var a=this._currentSourceSetting.getRelatedTr(),c=this._currentSourceSetting.getConfig();c._definition=this._currentSourceSetting.getDefinition();this._setRelatedConfig(a,c);this.sourceList.editRow(a,{name:c.name});this._currentSourceSetting.destroy()},_createNewQuerySourceSettingFromMenuItem:function(a,c){var b=new n({nls:this.nls,map:this.map,appConfig:this.appConfig});b.setDefinition(c);b.setConfig({url:a.url,name:a.name||"",layerId:a.layerId,placeholder:a.placeholder||
"",searchFields:a.searchFields||[],displayField:a.displayField||c.displayField||"",exactMatch:!!a.exactMatch,panToScale:a.panToScale||!1,zoomScale:a.zoomScale||this._defaultZoomScale,maxSuggestions:null===a.maxSuggestions||void 0===a.maxSuggestions?6:a.maxSuggestions,maxResults:a.maxResults||6,searchInCurrentMapExtent:!!a.searchInCurrentMapExtent,type:"query"});b._openQuerySourceChooser();b.own(e(b,"select-query-source-ok",d.hitch(this,function(a){(a=this.sourceList.addRow({name:a.name},0))&&a.success&&
(this._currentSourceSetting&&this._closeSourceSetting(),b.setRelatedTr(a.tr),b.placeAt(this.sourceSettingNode),this.sourceList.selectRow(a.tr),this._currentSourceSetting=b)})));b.own(e(b,"reselect-query-source-ok",d.hitch(this,function(a){var b=this._currentSourceSetting.getRelatedTr();this.sourceList.editRow(b,{name:a.name})})));b.own(e(b,"select-query-source-cancel",d.hitch(this,function(){this._currentSourceSetting!==b&&(b.destroy(),b=null)})))},_createNewQuerySourceSettingFromSourceList:function(a,
c,b){this._currentSourceSetting&&this._closeSourceSetting();this._currentSourceSetting=new n({nls:this.nls,map:this.map,appConfig:this.appConfig});this._currentSourceSetting.placeAt(this.sourceSettingNode);this._currentSourceSetting.setDefinition(c);this._currentSourceSetting.setConfig({url:a.url,name:a.name||"",layerId:a.layerId,placeholder:a.placeholder||"",searchFields:a.searchFields||[],displayField:a.displayField||c.displayField||"",exactMatch:!!a.exactMatch,panToScale:a.panToScale||!1,zoomScale:a.zoomScale||
this._defaultZoomScale,maxSuggestions:null===a.maxSuggestions||void 0===a.maxSuggestions?6:a.maxSuggestions,maxResults:a.maxResults||6,searchInCurrentMapExtent:!!a.searchInCurrentMapExtent,type:"query"});this._currentSourceSetting.setRelatedTr(b);this._currentSourceSetting.own(e(this._currentSourceSetting,"reselect-query-source",d.hitch(this,function(a){var b=this._currentSourceSetting.getRelatedTr();this.sourceList.editRow(b,{name:a.name})})))},_onSourceItemRemoved:function(a){this._checkConfig();
this._currentSourceSetting&&this._currentSourceSetting.getRelatedTr()===a&&(this._currentSourceSetting.destroy(),this._currentSourceSetting=null)},_onSourceItemSelected:function(a){var c=this._getRelatedConfig(a),b=this._currentSourceSetting&&this._currentSourceSetting.tr;c&&a!==b&&(this._currentSourceSetting&&!this._currentSourceSetting.isValidConfig()?(this._currentSourceSetting.showValidationTip(),this.sourceList.selectRow(b)):"query"===c.type?this._createNewQuerySourceSettingFromSourceList(c,
c._definition||{},a):"locator"===c.type&&this._createNewLocatorSourceSettingFromSourceList(c,c._definition||{},a))},_checkConfig:function(){0<this.sourceList.getRows().length?this.settingPagePopup.enableButton(0):this.settingPagePopup.disableButton(0)}})});