//>>built
define("dojo/_base/declare dojo/dom dojo/dom-construct dojo/dom-style dijit/registry jimu/BaseWidgetSetting dijit/_WidgetsInTemplateMixin dijit/form/Select dijit/form/NumberSpinner".split(" "),function(l,m,e,n,d,p,q,f){return l([p,q],{baseClass:"jimu-widget-ISImageSelector-setting",ISLayers:[],bandNames:[],requestFlag:!0,startup:function(){this.inherited(arguments);e.place('\x3cimg id\x3d"loadingImageSelectorSetting" style\x3d"position: absolute;top:0;bottom: 0;left: 0;right: 0;margin:auto;z-index:100;" src\x3d"'+
require.toUrl("jimu")+'/images/loading.gif"\x3e',this.domNode);n.set("loadingImageSelectorSetting","display","none");this.populatePage();this.setConfig(this.config)},postCreate:function(){this.inherited(arguments);var a=0,b=0,c;for(c in this.map.layerIds)if("ArcGISImageServiceLayer"===this.map.getLayer(this.map.layerIds[c]).type||this.map.getLayer(this.map.layerIds[c]).serviceDataType&&"esriImageService"===this.map.getLayer(this.map.layerIds[c]).serviceDataType.substr(0,16)){var d=this.map.getLayer(this.map.layerIds[c]).arcgisProps?
this.map.getLayer(this.map.layerIds[c]).arcgisProps.title:"";if("_"!==d.charAt(d.length-1)){for(this.ISLayers[a]=this.map.getLayer(this.map.layerIds[c]);this.map.itemInfo.itemData.operationalLayers[b]&&this.map.itemInfo.itemData.operationalLayers[b].url!==this.ISLayers[a].url;)b++;this.map.itemInfo.itemData.operationalLayers[b]&&this.map.itemInfo.itemData.operationalLayers[b].title?this.ISLayers[a].title=this.map.itemInfo.itemData.operationalLayers[b].title:this.map.getLayer(this.map.layerIds[c]).name?
this.ISLayers[a].title=this.map.getLayer(this.map.layerIds[c]).name:this.map.getLayer(this.map.layerIds[c]).id?this.ISLayers[a].title=this.map.getLayer(this.map.layerIds[c]).id:this.ISLayers[a].title="Layer"+a;a++}}},setConfig:function(a){this.config=a;for(var b in this.ISLayers){var c=this.ISLayers[b].id;a[c]&&(void 0!==a[c].imageField&&d.byId("imageField_"+b).set("value",a[c].imageField),void 0!==a[c].objectID&&d.byId("objectID_"+b).set("value",a[c].objectID),void 0!==a[c].catgory&&d.byId("category_"+
b).set("value",a[c].category))}},getConfig:function(){for(var a in this.ISLayers){var b={imageField:d.byId("imageField_"+a).get("value"),objectID:d.byId("objectID_"+a).get("value"),category:d.byId("category_"+a).get("value"),title:this.ISLayers[a].title};this.config[this.ISLayers[a].id]=b}this.config.display=d.byId("userInterfaceOption").get("value");this.config.zoomLevel=this.selectorZoomLevelInput.get("value");this.config.searchExtent=this.selectorSearchExtentInput.get("value");this.config.listImagesSeparate=
this.listImagesSeparate.get("value");this.config.autoRefresh=this.selectorAutoRefresh.get("checked");return this.config},populatePage:function(){for(var a in this.ISLayers){var b=e.create("tbody",{innerHTML:"\x3ctr\x3e\x3ctd\x3e"+this.ISLayers[a].title+'\x3c/td\x3e\x3c/tr\x3e\x3ctr style\x3d"display:none;"\x3e\x3ctd class\x3d"first"\x3eObject ID\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3cselect id\x3d"objectID_'+a+'"\x3e\x3c/select\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr\x3e\x3ctd class\x3d"first"\x3eSelect using\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3cselect id\x3d"imageField_'+
a+'"\x3e\x3c/select\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr style\x3d"display:none;"\x3e\x3ctd class\x3d"first"\x3eCategory\x3c/td\x3e\x3ctd class\x3d"second"\x3e\x3cselect id\x3d"category_'+a+'"\x3e\x3c/select\x3e\x3c/td\x3e\x3c/tr\x3e'});e.place(b,m.byId("setting-table"));(new f({style:"margin:10px;"},"imageField_"+a)).startup();(new f({style:"margin:10px;"},"objectID_"+a)).startup();(new f({style:"margin:10px;"},"category_"+a)).startup()}this.setValues()},setValues:function(){for(var a=0;a<this.ISLayers.length;a++)this._populateDropDown(d.byId("imageField_"+
a),this.ISLayers[a].fields,"",new RegExp(/acq[a-z]*[_]?Date/i)),this._populateDropDown(d.byId("objectID_"+a),this.ISLayers[a].fields,"esriFieldTypeOID",new RegExp(/O[a-z]*[_]?ID/i)),this._populateDropDown(d.byId("category_"+a),this.ISLayers[a].fields,"esriFieldTypeInteger",new RegExp(/C[a-z]*/i))},_populateDropDown:function(a,b,c,d){var e=[{label:"Select field",value:""}],f=1,h="";if(b)for(var g in b)if(b[g].type===c||!c){e[f]={label:b[g].name,value:b[g].name};var k=b[g].name;""===h&&d.test(k)&&(h=
k);f++}a.addOption(e);a.set("value",h)}})});