//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/on dojo/keys dojo/query dojo/cookie dijit/_WidgetsInTemplateMixin jimu/BaseWidget dojo/topic jimu/dijit/CheckBox jimu/utils esri/lang jimu/dijit/LoadingShelter dojo/Deferred".split(" "),function(p,f,b,k,h,l,g,q,r,m,t,d,n,u,v){return p([r,q],{baseClass:"jimu-widget-splash",_hasContent:null,_requireConfirm:null,_isClosed:!1,postCreate:function(){this.inherited(arguments);b.setAttr(this.domNode,"aria-label",this.nls._widgetLabel);this.shelter=
new u({hidden:!0});this.shelter.placeAt(this.domNode);this.shelter.startup();this._hasContent=this.config.splash&&this.config.splash.splashContent;this._requireConfirm=this.config.splash&&this.config.splash.requireConfirm;this._showOption=this.config.splash&&this.config.splash.showOption;this._confirmEverytime=this.config.splash&&this.config.splash.confirmEverytime;this._hasContent&&(this.customContentNode.innerHTML=this.config.splash.splashContent);if(this._requireConfirm||this._showOption){var a=
"";this._requireConfirm?(a=this.config.splash.confirm.text,b.addClass(this.okNode,"disable-btn")):(a=this.nls.notShowAgain,b.addClass(this.okNode,"enable-btn"));this.confirmCheck=new t({label:d.stripHTML(a),checked:!1},this.confirmCheck);this.own(k(this.confirmCheck,"change",f.hitch(this,this.onCheckBoxClick)));this.confirmCheck.startup()}else b.setStyle(this.confirmCheck,"display","none"),b.addClass(this.okNode,"enable-btn")},onOpen:function(){if(!d.isInConfigOrPreviewWindow()){var a=this._getCookieKey(),
a=g(a);n.isDefined(a)&&"false"===a.toString()&&this.close()}this._requireConfirm||this._showOption?this.confirmCheck.focus():this.okNode.focus();this._eventShow()},startup:function(){this.inherited(arguments);this.shelter.show();this._normalizeDomNodePosition();this._setConfig();this.own(k(this.domNode,"keydown",f.hitch(this,function(a){b.hasClass(a.target,this.baseClass)&&a.keyCode===h.ESCAPE&&this.close()})));this.own(k(this.splashDesktop,"keydown",f.hitch(this,function(a){b.hasClass(a.target,"jimu-widget-splash-desktop")&&
(a.keyCode===h.TAB&&a.preventDefault(),(a.keyCode===h.ENTER||!a.shiftKey&&a.keyCode===h.TAB)&&d.focusFirstFocusNode(this.domNode))})));for(var a=d.getFocusNodesInDom(this.domNode),c=0;c<a.length;c++)b.setAttr(a[c],"tabindex",0);d.initFirstFocusNode(this.domNode,a[0]);d.initLastFocusNode(this.domNode,this.okNode)},_setConfig:function(){this._setWidthForOldVersion().then(f.hitch(this,function(){this._setSizeFromConfig();var a=this.config.splash.button;"undefined"!==typeof a&&("undefined"!==typeof a.color&&
(b.setStyle(this.okNode,"backgroundColor",a.color),b.setStyle(this.okNode,"color",d.invertColor(a.color))),"undefined"!==typeof a.transparency&&b.setStyle(this.okNode,"opacity",1-a.transparency));this.okNode.innerHTML=this.config.splash.button.text||this.nls.ok;b.attr(this.okNode,"title",this.config.splash.button.text||this.nls.ok);var c=this.config.splash.background;if("undefined"!==typeof c)if("image"===c.mode&&"undefined"!==typeof c.image){var e=a="",a="url("+d.processUrlInWidgetConfig(c.image,
this.folderUrl)+") center center ",e="no-repeat",c=c.type;"undefined"!==typeof c&&(b.addClass(this.splashContainerNode,c),"tile"===c&&(e="repeat"));b.setStyle(this.splashContainerNode,"background",a+e)}else"color"===c.mode&&"undefined"!==typeof c.color&&("undefined"!==typeof c.color&&b.setStyle(this.splashContainerBackground,"backgroundColor",c.color),"undefined"!==typeof c.transparency&&b.setStyle(this.splashContainerBackground,"opacity",1-c.transparency));a=this.config.splash.confirm;"undefined"!==
typeof a&&this.domNode&&(e=l(".label",this.domNode)[0],"undefined"!==typeof a.color&&e&&b.setStyle(e,"color",a.color),"undefined"!==typeof a.transparency&&e&&b.setStyle(e,"opacity",1-a.transparency));this.contentVertical="undefined"!==typeof this.config.splash.contentVertical?this.config.splash.contentVertical:"top";d.isInConfigOrPreviewWindow()||(a=this._getCookieKey(),a=g(a),n.isDefined(a)&&"false"===a.toString()&&this.close());this.resize();this.own(k(window,"resize",f.hitch(this,function(){this.resize()})));
this._resizeContentImg();b.removeClass(this.envelopeNode,"buried");this.shelter.hide()}))},_normalizeDomNodePosition:function(){b.setStyle(this.domNode,"top",0);b.setStyle(this.domNode,"left",0);b.setStyle(this.domNode,"right",0);b.setStyle(this.domNode,"bottom",0)},setPosition:function(a){this.position=a;b.place(this.domNode,window.jimuConfig.layoutId);this._normalizeDomNodePosition();this.started&&this.resize()},resize:function(){this._changeStatus()},_resizeContentImg:function(){if(this._hasContent&&
!this._isClosed){var a=b.getContentBox(this.envelopeNode);b.empty(this.customContentNode);var c=b.toDom(this.config.splash.splashContent);b.place(c,this.customContentNode);this.customContentNode.nodeType&&1===this.customContentNode.nodeType&&(c=l("img",this.customContentNode))&&c.length&&c.style({maxWidth:a.w-40-20+"px",maxHeight:a.h-40+"px"})}},_changeStatus:function(){window.appInfo.isRunInMobile?(b.setStyle(this.envelopeNode,"height","100%"),b.setStyle(this.envelopeNode,"width","100%")):this._setSizeFromConfig();
this._resizeCustomContent();this._resizeContentImg()},_getNodeStylePx:function(a,c){return a&&c?parseInt(b.getStyle(a,c),10):0},_resizeCustomContent:function(){var a=b.getContentBox(this.splashContainerNode),c=this.customContentNode.scrollHeight,e=b.getMarginBox(this.footerNode),d=this._getNodeStylePx(this.customContentNode,"margin-bottom"),f=this._getNodeStylePx(this.footerNode,"bottom"),a=a.h-(e.h+f);!0===c>=a||window.appInfo.isRunInMobile?b.setStyle(this.customContentNode,"height",a-d+"px"):(b.setStyle(this.customContentNode,
"height","auto"),this._moveContentToMiddle({contentSpace:a,customContentScrollheight:c}))},_moveContentToMiddle:function(a){var c=(a.contentSpace-10)/2;"middle"===this.contentVertical&&(a=a.customContentScrollheight/2-c,0>a?b.setStyle(this.customContentNode,"marginTop",Math.abs(a)+10+"px"):b.setStyle(this.customContentNode,"marginTop","10px"))},onCheckBoxClick:function(){this._requireConfirm&&(this.confirmCheck.getValue()?(b.addClass(this.okNode,"enable-btn"),b.removeClass(this.okNode,"disable-btn")):
(b.addClass(this.okNode,"disable-btn"),b.removeClass(this.okNode,"enable-btn")))},_getCookieKey:function(){return"isfirst_"+encodeURIComponent(d.getAppIdFromUrl())},onOkClick:function(){var a=this._getCookieKey();this._requireConfirm?this.confirmCheck.getValue()&&(d.isInConfigOrPreviewWindow()||this._confirmEverytime?g(a,null,{expires:-1}):g(a,!1,{expires:1E3,path:"/"}),this.close()):(this._showOption?!d.isInConfigOrPreviewWindow()&&this.confirmCheck.getValue()&&g(a,!1,{expires:1E3,path:"/"}):g(a,
null,{expires:-1}),this.close())},onOkKeydown:function(a){a.keyCode===h.ENTER&&(this.onOkClick(),d.trapToNextFocusContainer(this.domNode,!0))},close:function(){this._isClosed=!0;this._eventHide();this.widgetManager.closeWidget(this)},_setSizeFromConfig:function(){var a=this.config.splash.size;if("undefined"!==typeof a&&"object"===typeof a){var c=a.percent,d=a.wh;"percent"===a.mode&&"undefined"!==typeof c?(b.setStyle(this.envelopeNode,"width",c),b.setStyle(this.envelopeNode,"height",c)):"wh"===a.mode&&
"undefined"!==typeof d&&(this._setWidthInCurrentScreen(d),this._setHeightInCurrentScreen(d))}},_setWidthInCurrentScreen:function(a){var c=window.innerWidth;!window.appInfo.isRunInMobile&&a.w<=c?b.setStyle(this.envelopeNode,"width",a.w+"px"):b.setStyle(this.envelopeNode,"width","100%")},_setHeightInCurrentScreen:function(a){var c=window.innerHeight;!window.appInfo.isRunInMobile&&a.h<=c?b.setStyle(this.envelopeNode,"height",a.h+"px"):b.setStyle(this.envelopeNode,"height","100%")},_setWidthForOldVersion:function(){var a=
new v,b=this.config.splash.size;if(!0===("wh"===b.mode&&"undefined"!==typeof b.wh&&null===b.wh.h))return d.getEditorContentHeight(this.config.splash.splashContent,this.domNode,{contentWidth:560,contentMarginTop:20,footerHeight:98}).then(f.hitch(this,function(a){return b.wh.h=a}));a.resolve();return a},_eventShow:function(){setTimeout(f.hitch(this,function(){m.publish("splashPopupShow")}),800)},_eventHide:function(){m.publish("splashPopupHide")}})});