//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/on dojo/aspect dojo/query dojo/keys dojo/json esri/request jimu/BaseWidgetSetting dijit/_WidgetsInTemplateMixin jimu/dijit/SimpleTable jimu/dijit/Message jimu/dijit/Popup jimu/dijit/CheckBox jimu/dijit/LoadingIndicator jimu/portalUtils ./Edit jimu/SpatialReference/srUtils jimu/dijit/RadioBtn dojo/NodeList-dom dijit/form/NumberSpinner dijit/form/NumberTextBox".split(" "),function(q,f,l,h,r,g,m,k,t,u,v,w,n,x,y,p,z,A,e){return q([u,v],{baseClass:"jimu-widget-coordinate-setting",
edit:null,popup:null,popupState:"",editTr:null,gsVersion:0,postCreate:function(){this.inherited(arguments);this.separator=new y({label:this.nls.separator,checked:!1},this.separator);this.shelter1=new p({hidden:!0});this.shelter1.placeAt(this.domNode);this.shelter1.startup();this.shelter2=new p({hidden:!0});this.shelter2.placeAt(this.domNode);this.shelter2.startup()},startup:function(){this.inherited(arguments);this.outputCoordinateTable=new w({autoHeight:!1,fields:[{name:"id",title:this.nls.id,type:"text",
unique:!0,hidden:!0,editable:!1},{name:"wkid",title:this.nls.wkid,type:"text","class":"wkid",hidden:!0,editable:!1},{name:"isDefault",title:this.nls.defaultTitle,type:"radio",editable:!0,width:"100px"},{name:"label",title:this.nls.label,type:"text",editable:!1},{name:"alias",title:this.nls.alias,type:"text",editable:!0},{name:"outputUnit",title:this.nls.output,type:"text",hidden:!0,editable:!1},{name:"transformationWkid",title:this.nls.transformationWkid,type:"text","class":"transformationWkid",editable:!1,
hidden:!0},{name:"transformationLabel",title:this.nls.transformationLabel,type:"text",editable:!1,hidden:!0},{name:"transformForward",title:this.nls.transformForward,type:"checkbox",editable:!1,hidden:!0},{name:"options",title:"options",type:"text",editable:!1,hidden:!0},{name:"actions",title:this.nls.actions,type:"actions","class":"actions",actions:["edit","up","down","delete"]}],selectable:!1,singleClickEdit:!0});l.setStyle(this.outputCoordinateTable.domNode,"height","100%");this.outputCoordinateTable.placeAt(this.tableCoordinate);
this.outputCoordinateTable.startup();this.own(h(this.outputCoordinateTable,"actions-edit",f.hitch(this,"onEditClick")));this.setConfig(this.config);this._initOrderLonLatRadioBtns();this._getGeometryServiceVersion()},setConfig:function(a){this.config=a;this.outputCoordinateTable.clear();this.shelter1.show();e.loadResource().then(f.hitch(this,function(){if(a.spatialReferences&&a.spatialReferences.length){for(var c=[],b=a.spatialReferences.length,d=0;d<b;d++){var f=parseInt(a.spatialReferences[d].wkid,
10),g=a.spatialReferences[d].isDefault,h=a.spatialReferences[d].alias;c.push({id:d,wkid:e.standardizeWkid(f),isDefault:g||!1,label:a.spatialReferences[d].label,alias:h||a.spatialReferences[d].label,outputUnit:a.spatialReferences[d].outputUnit,transformationWkid:a.spatialReferences[d].transformationWkid,transformationLabel:a.spatialReferences[d].transformationLabel,transformForward:a.spatialReferences[d].transformForward,options:k.stringify(a.spatialReferences[d].options)})}this.outputCoordinateTable.addRows(c)}else this._addMapCoordinate()}),
f.hitch(this,function(a){console.error(a)})).always(f.hitch(this,function(){this.shelter1.hide()}));isFinite(parseInt(a.decimalPlaces,10))&&this.spinner.set("value",parseInt(a.decimalPlaces,10));a.addSeparator&&this.separator.setValue(a.addSeparator)},_getGeometryServiceVersion:function(){this.shelter2.show();if(esriConfig.defaults.geometryService&&esriConfig.defaults.geometryService.url){var a=esriConfig.defaults.geometryService.url,a=a.slice(0,a.indexOf("/Geometry/"));t({url:a,handleAs:"json",callbackParamName:"callback",
content:{f:"json"}}).then(f.hitch(this,function(a){console.log(a);a&&a.currentVersion&&(this.gsVersion=parseFloat(a.currentVersion))}),f.hitch(this,function(a){console.error(a)})).always(f.hitch(this,function(){this.shelter2.hide()}))}else this.shelter2.hide(),new n({message:this.nls.getVersionError})},_addMapCoordinate:function(){var a=this.map.spatialReference.wkid;z.getUnits(this.appConfig.portalUrl).then(f.hitch(this,function(c){if(e.isValidWkid(a)){var b={wkid:e.standardizeWkid(a),label:e.getSRLabel(parseInt(a,
10))};b.alias=b.label;e.isProjectedCS(b.wkid)?b.outputUnit="english"===c?"FOOT":"METER":b.outputUnit=b.outputUnit||e.getCSUnit(b.wkid);c={sameSRWithMap:e.isSameSR(b.wkid,this.map.spatialReference.wkid),isGeographicCS:e.isGeographicCS(b.wkid),isGeographicUnit:e.isGeographicUnit(b.outputUnit),isProjectedCS:e.isProjectedCS(b.wkid),isProjectUnit:e.isProjectUnit(b.outputUnit),spheroidCS:e.isProjectedCS(b.wkid)?e.getGeoCSByProj(b.wkid):b.wkid,defaultUnit:e.getCSUnit(b.wkid),unitRate:e.getUnitRate(e.getCSUnit(b.wkid),
b.outputUnit)};this.map.spatialReference.isWebMercator()&&(c.isGeographicUnit=!0,c.isProjectUnit=!1,c.unitRate=1,b.outputUnit="DECIMAL_DEGREES");"DEGREES_DECIMAL_MINUTES"===b.outputUnit&&(c.isGeographicUnit=!0,c.unitRate=1);b.options=k.stringify(c);this.outputCoordinateTable.addRow(b)}}))},_keepDefaultOnlyEdit:function(){var a=g("."+this.baseClass+" .body-section tr[rowid\x3drow1]")[0];g(".action-item",a).style("display","none");g(".row-edit-div",a).style("display","block");r.after(this.outputCoordinateTable,
"onBeforeRowUp",f.hitch(this,function(a){if(g(".body-section .simple-table-row")[1]===a)return!1}),!0)},onAddClick:function(){this.popupState="ADD";this._openEdit(this.nls.add,{})},onEditClick:function(a){var c=this.outputCoordinateTable.getRowData(a);this.popupState="EDIT";this.editTr=a;this._openEdit(this.nls.edit,c)},_openEdit:function(a,c){this.edit=new A({version:this.gsVersion,map:this.map,nls:this.nls});this.popup=new x({titleLabel:a,autoHeight:!0,content:this.edit,container:"main-page",width:640,
buttons:[{label:this.nls.ok,key:m.ENTER,disable:!0,onClick:f.hitch(this,"_onEditOk")},{label:this.nls.cancel,classNames:["jimu-btn-vacation"],key:m.ESCAPE}],onClose:f.hitch(this,"_onEditClose")});this.edit.setConfig(c||{});l.addClass(this.popup.domNode,"widget-setting-popup");this.edit.startup()},_onEditOk:function(){var a=this.edit.getConfig(),c=null;a.wkid=e.standardizeWkid(a.wkid);a.options=k.stringify(a.options);a.label&&(a.alias=a.label);"ADD"===this.popupState?c=this.outputCoordinateTable.addRow(a):
"EDIT"===this.popupState&&(c=this.outputCoordinateTable.editRow(this.editTr,a));c.success?(this.popup.close(),this.popupState="",this.editTr=null):new n({message:a.wkid+this.nls[c.errorCode]})},_onEditClose:function(){this.popup=this.edit=null},getConfig:function(){for(var a=this.outputCoordinateTable.getData(),c=[],b=a.length,d=0;d<b;d++)delete a[d].id,a[d].options=k.parse(a[d].options),c.push(a[d]);this.config.spatialReferences=c;this.config.decimalPlaces=this.spinner.get("value");this.config.addSeparator=
this.separator.getValue();return this.config},_initOrderLonLatRadioBtns:function(){this.own(h(this.lonLat,"click",f.hitch(this,function(){this.config.displayOrderLonLat=!0})));this.own(h(this.latLon,"click",f.hitch(this,function(){this.config.displayOrderLonLat=!1})));this.config.displayOrderLonLat?(this.lonLat.set("checked",!0),this.config.displayOrderLonLat=!0):(this.latLon.set("checked",!0),this.config.displayOrderLonLat=!1)}})});