//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/aspect dojo/query dojo/on dojo/Deferred dojo/mouse dojo/dom-construct dojo/dom-geometry jimu/BaseWidget jimu/PoolControllerMixin jimu/tokenUtils jimu/portalUtils jimu/portalUrlUtils jimu/utils jimu/dijit/Message ./PopupTileNodes dojo/NodeList-manipulate".split(" "),function(t,e,h,c,m,g,k,p,u,q,v,w,x,n,y,r,f,z,A){return t([w,x],{baseClass:"jimu-widget-header-controller jimu-main-background",maxIconCount:-1,createMoreIcon:!1,
switchableElements:{},height:40,openedId:"",moveTopOnActive:!1,postCreate:function(){this.inherited(arguments);this._processGroupSetting();this.switchableElements.title=this.titleNode;this.switchableElements.links=this.linksNode;this.switchableElements.subtitle=this.subtitleNode;this.position&&this.position.height&&(this.height=this.position.height);c.setStyle(this.signInSectionNode,"display","none");this.appConfig&&this.appConfig.logo?(this.logoNode.src=this.appConfig.logo,c.removeClass(this.logoNode,
"hide-logo")):(this.logoNode.src="",c.addClass(this.logoNode,"hide-logo"));this.switchableElements.title.innerHTML=f.sanitizeHTML(this.appConfig.title?this.appConfig.title:"");this.switchableElements.subtitle.innerHTML=f.sanitizeHTML(this.appConfig.subtitle?this.appConfig.subtitle:"");this._createDynamicLinks(this.appConfig.links);this._setElementsSize();this.own(k(this.domNode,u.enter,e.hitch(this,function(){var a="",b=r.getServerByUrl(this.appConfig&&this.appConfig.portalUrl||"");r.isArcGIScom(b)&&
(b="ArcGIS.com");b&&(a=this.nls.signInTo+" "+b);this.signinLinkNode.title=a})))},startup:function(){this.inherited(arguments);this.resize()},onAction:function(a,b){"highLight"===a&&b&&(b=g('div[settingid\x3d"'+b.widgetId+'"]',this.domNode)[0],this._highLight(b));"removeHighLight"===a&&this._removeHighLight()},onSignIn:function(a){this.inherited(arguments);c.setStyle(this.signinLinkNode,"display","none");c.setStyle(this.userNameLinkNode,"display","");c.setStyle(this.signoutLinkNode,"display","");this.userNameLinkNode.innerHTML=
a.userId;c.setAttr(this.userNameLinkNode,"href",this.appConfig.portalUrl+"home/user.html");this.popupLinkNode&&(c.setStyle(this.popupSigninNode,"display","none"),c.setStyle(this.popupUserNameNode,"display",""),c.setStyle(this.popupSignoutNode,"display",""),g("a",this.popupUserNameNode).html(a.userId).attr("href",this.appConfig.portalUrl+"home/user.html"));this.resize()},onSignOut:function(){this.inherited(arguments);this._onSignOut(this.nls.signin);y.getPortal(this.appConfig.portalUrl).loadSelfInfo().then(e.hitch(this,
function(a){this._onSignOut(this.nls.signInTo+" "+a.name)}),e.hitch(this,function(a){console.error(a)}))},_onSignOut:function(a){c.setStyle(this.signinLinkNode,"display","");c.setAttr(this.signinLinkNode,"innerHTML",a);c.setStyle(this.userNameLinkNode,"display","none");c.setStyle(this.signoutLinkNode,"display","none");this.userNameLinkNode.innerHTML="";this.popupLinkNode&&(c.setStyle(this.popupSigninNode,"display",""),c.setAttr(this.popupSigninNode,"innerHTML",a),c.setStyle(this.popupUserNameNode,
"display","none"),c.setStyle(this.popupSignoutNode,"display","none"),g("a",this.popupUserNameNode).html(""));this.resize()},resize:function(){var a=c.getStyle(this.headerNode,"float"),b=c.getStyle(this.logoNode,"float"),d=c.getStyle(this.titlesNode,"float"),l=c.getStyle(this.linksNode,"float");a&&"none"!==a&&b&&"none"!==b&&d&&"none"!==d&&l&&"none"!==l?this._resize():setTimeout(e.hitch(this,this.resize),200)},_resize:function(){var a=c.getContentBox(this.domNode);this._showSwitchableElements(["title",
"links","subtitle"]);this._createIconNodes(a);this.morePane&&this.morePane.resize();this.popupLinkNode&&c.setStyle(jimuConfig.layoutId,{left:c.getContentBox(this.popupLinkNode).w+"px"})},destroy:function(){this.timeoutHandle&&(clearTimeout(this.timeoutHandle),this.timeoutHandle=null);this.morePane&&this.morePane.destroy();this.moreIconPaneCoverNode&&(c.destroy(this.moreIconPaneCoverNode),this.moreIconPaneCoverNode=null);this.popupLinkNode&&this.popupLinksVisible&&this._hidePopupLink();c.destroy(this.popupLinkNode);
this.inherited(arguments)},onAppConfigChanged:function(a,b,c){switch(b){case "attributeChange":this._onAttributeChange(a,c);break;default:return}this.appConfig=a;this.resize()},getOpenedIds:function(){this.inherited(arguments);return""===this.openedId?[]:[this.openedId]},setOpenedIds:function(a){if(0!==a.length){var b=this.getConfigById(a[0]);b&&(this.openedId=a[0],b.widgets&&"openAll"===b.openType?this._showIconContent(b):b.widgets||this._showIconContent(b))}},_onLogoLoad:function(){this.resize()},
_highLight:function(a){this.hlDiv&&this._removeHighLight();if(a){var b=v.getMarginBox(a);this.hlDiv=q.create("div",{style:{position:"absolute",left:b.l+"px",top:b.t+"px",width:b.w+"px",height:b.h+"px"},"class":"icon-highlight"},a,"before")}},_removeHighLight:function(){this.hlDiv&&(q.destroy(this.hlDiv),this.hlDiv=null)},_onAttributeChange:function(a,b){"title"in b&&b.title!==this.appConfig.title&&(this.titleNode.innerHTML=f.sanitizeHTML(b.title));"subtitle"in b&&b.subtitle!==this.appConfig.subtitle&&
(this.subtitleNode.innerHTML=f.sanitizeHTML(b.subtitle));"logo"in b&&b.logo!==this.appConfig.logo&&(b.logo?(c.setAttr(this.logoNode,"src",b.logo),c.removeClass(this.logoNode,"hide-logo")):(c.removeAttr(this.logoNode,"src"),c.addClass(this.logoNode,"hide-logo")));"links"in b&&this._createDynamicLinks(b.links)},_setElementsSize:function(){c.setStyle(this.logoNode,{height:"30px",marginTop:(this.height-30)/2+"px"});c.setStyle(this.titleNode,{lineHeight:this.height+"px"});c.setStyle(this.subtitleNode,
{lineHeight:this.height+"px"});g(".jimu-link",this.domNode).style({lineHeight:this.height+"px"})},_processGroupSetting:function(){h.forEach(this.appConfig.widgetPool.groups,function(a){var b;a:{if(this.config.groupSetting)for(b=0;b<this.config.groupSetting.length;b++)if(this.config.groupSetting[b].label===a.label){b=this.config.groupSetting[b].type;break a}b="openAll"}a.openType=b},this)},_createDynamicLinks:function(a){if(window.isRTL){var b=[];h.forEach(a,function(a){b.unshift(a)});a=b}c.empty(this.dynamicLinksNode);
h.forEach(a,function(a){c.create("a",{href:a.url,target:"_blank",innerHTML:f.sanitizeHTML(a.label),"class":"jimu-link jimu-align-leading jimu-leading-margin1",style:{lineHeight:this.height+"px"}},this.dynamicLinksNode)},this)},_showSwitchableElements:function(a){var b=this.switchableElements,d;for(d in b)b.hasOwnProperty(d)&&(-1<a.indexOf(d)?(c.setStyle(b[d],"display","block"),b[d].visible=!0):(c.setStyle(b[d],"display","none"),b[d].visible=!1));this.logoClickHandle&&this.logoClickHandle.remove();
0>a.indexOf("links")?this.logoClickHandle=k(this.logoNode,"click",e.hitch(this,this._onLogoClick)):(this.popupLinksVisible&&this._hidePopupLink(),c.setStyle(this.logoNode,{cursor:"default"}))},_switchSignin:function(){var a=n.getPortalCredential(this.appConfig.portalUrl);if(a)this.onSignIn(a);else this.onSignOut()},_onLogoClick:function(){this.popupLinkNode&&c.destroy(this.popupLinkNode);this.popupLinkNode=this._createPopupLinkNode();this.popupLinksVisible?this._hidePopupLink():this._showPopupLink()},
_hidePopupLink:function(){c.setStyle(this.popupLinkNode,"display","none");window.isRTL?c.setStyle(jimuConfig.layoutId,{right:0}):c.setStyle(jimuConfig.layoutId,{left:0});this.popupLinksVisible=!1},_showPopupLink:function(){c.setStyle(this.popupLinkNode,"display","");window.isRTL?c.setStyle(jimuConfig.layoutId,{right:c.getContentBox(this.popupLinkNode).w+"px"}):c.setStyle(jimuConfig.layoutId,{left:c.getContentBox(this.popupLinkNode).w+"px"});this.popupLinksVisible=!0},_createPopupLinkNode:function(){var a,
b;c.getContentBox(jimuConfig.mainPageId);a=c.create("div",{"class":"popup-links jimu-main-background",style:{position:"absolute",zIndex:100,top:0,bottom:0}},jimuConfig.mainPageId);window.isRTL?c.setStyle(a,{right:0,left:"50px"}):c.setStyle(a,{left:0,right:"50px"});b=c.create("div",{"class":"popup-title",style:{height:this.height+"px",width:"100%"}},a);var d=c.create("img",{"class":"logo jimu-float-leading jimu-leading-margin1",src:this.appConfig.logo?this.appConfig.logo:this.folderUrl+"images/app-logo.png",
style:{width:"30px",height:"30px",marginTop:(this.height-30)/2+"px"}},b),l=c.create("div",{"class":"title jimu-float-leading jimu-leading-margin1 jimu-ellipsis",innerHTML:f.sanitizeHTML(this.appConfig.title),style:{lineHeight:this.height+"px"}},b),e="auto";try{e=c.getMarginBox(b).w-c.getMarginBox(d).w-c.getMarginExtents(l).w+"px"}catch(B){console.error(B),e="auto"}c.setStyle(l,"width",e);h.forEach(this.appConfig.links,function(b){this._createLinkNode(a,b,!1)},this);this._createLinkNode(a,{label:"",
url:"#"},!1);return a},_createLinkNode:function(a,b,d){a=c.place('\x3cdiv class\x3d"jimu-link"\x3e\x3c/div\x3e',a);c.place('\x3cdiv class\x3d"line"\x3e\x3c/div\x3e',a);d=c.place('\x3cdiv class\x3d"'+(d?"link-section signin":"link-section")+'"\x3e\x3c/div\x3e',a);c.create("a",{href:b.url,"class":"jimu-ellipsis",target:"_blank",innerHTML:f.sanitizeHTML(b.label),title:b.label,style:{lineHeight:"66px"}},d);return a},_onSigninClick:function(){n.signInPortal(this.appConfig.portalUrl,this.appConfig.appId)},
_onSignoutClick:function(){this.appConfig.mode?new z({message:this.nls.cantSignOutTip}):n.signOutAll()},_onUserNameClick:function(){},_getHeaderSectionWidth:function(){return c.getMarginBox(this.headerNode).w},_getContainerWidth:function(a){var b=this._getHeaderSectionWidth();return a.w-b-this._getEmptyWidth(a)},_calcContainerAndEmptyWidth:function(a){var b=this._getContainerWidth(a),c=this._getEmptyWidth(a);b<2*this.iconWidth&&(this.switchableElements.subtitle.visible?(this._showSwitchableElements(["title",
"links"]),b=this._getContainerWidth(a),b<2*this.iconWidth&&(this._showSwitchableElements(["title"]),b=this._getContainerWidth(a),b<2*this.iconWidth&&(this._showSwitchableElements([]),b=this._getContainerWidth(a),b<2*this.iconWidth&&(c-=2*this.iconWidth-b,b=2*this.iconWidth,this._getContainerWidth(a))))):(this._showSwitchableElements([]),b=this._getContainerWidth(a),b<2*this.iconWidth&&(c-=2*this.iconWidth-b,b=2*this.iconWidth)));return{containerWidth:b,emptyWidth:c}},_getEmptyWidth:function(a){return.1*
a.w},_createIconNodes:function(a){g(".icon-node",this.containerNode).remove();this._closeDropMenu();var b,d=this.getAllConfigs();this.iconWidth=a.h;a=this._calcContainerAndEmptyWidth(a);b={width:a.containerWidth+"px"};b[window.isRTL?"marginRight":"marginLeft"]=a.emptyWidth-5+"px";c.setStyle(this.containerNode,b);this.maxIconCount=Math.floor(a.containerWidth/this.iconWidth);this.maxIconCount>=d.length?(this.headerIconCount=d.length,this.createMoreIcon=!1):(this.headerIconCount=this.maxIconCount-1,
this.createMoreIcon=!0);this.createMoreIcon&&this._createIconNode({label:this.nls.more,name:"__more"});var e;for(a=this.headerIconCount-1;0<=a;a--){b=d[a];var f=this._createIconNode(b);b.openAtStart&&(e=f)}e&&!this.openAtStartWidget&&(this._onIconClick(e),this.openAtStartWidget=e.config.name);this.openedId&&this.getConfigById(this.openedId)&&!1===this.getConfigById(this.openedId).inPanel&&(d=this._getIconNodeById(this.openedId),e=this.widgetManager.getWidgetById(this.openedId),d&&e?this._setOffPanelWidgetPosition(d,
e):(this.widgetManager.closeWidget(this.openedId),this.openedId=""))},_createIconNode:function(a){var b,d;d=a.label===this.nls.more?this.folderUrl+"images/more_icon.png":a.icon;b=c.create("div",{"class":"icon-node jimu-float-trailing",title:a.label,settingId:a.id,style:{width:this.height+"px",height:this.height+"px"},"data-widget-name":a.name},this.containerNode);c.create("img",{src:d,style:{marginTop:(this.height-24)/2+"px"}},b);a.label===this.nls.more?k(b,"click",e.hitch(this,this._showMorePane,
a)):k(b,"click",e.hitch(this,function(){this._onIconClick(b)}));b.config=a;b.config.widgets&&1<b.config.widgets.length&&"dropDown"===b.config.openType&&this._createDropTriangle(b);return b},_createDropTriangle:function(a){var b=c.getMarginBox(a);c.create("div",{"class":"drop-triangle",style:{left:b.l+b.w/2-4+"px"}},a)},_onIconClick:function(a){a.config.widgets&&1!==a.config.widgets.length&&"openAll"!==a.config.openType?this.dropMenuNode?this._closeDropMenu():this._openDropMenu(a):this.openedId&&this.openedId===
a.config.id?this._switchNodeToClose(this.openedId):this.openedId?this._switchNodeToClose(this.openedId).then(e.hitch(this,function(){this._closeDropMenu();this._switchNodeToOpen(a.config.id)})):(this._switchNodeToOpen(a.config.id),console.log(a.config.id))},_closeDropMenu:function(){this.dropMenuNode&&(c.destroy(this.dropMenuNode),this.dropMenuNode=null)},_openDropMenu:function(a){this.dropMenuNode=c.create("div",{"class":"jimu-drop-menu jimu-main-background",title:a.config.label,style:{position:"absolute",
zIndex:"101"}});c.place(this.dropMenuNode,this.containerNode);h.forEach(a.config.widgets,function(a){this._createDropMenuItem(a)},this);this._setDropMenuPosition(a);this.morePane&&this.morePane.hide()},_createDropMenuItem:function(a){var b=c.create("div",{"class":"menu-item",title:a.label,style:{height:this.height+"px"}},this.dropMenuNode);c.create("img",{"class":"jimu-float-leading",src:a.icon},b);c.create("div",{"class":"label jimu-float-leading",innerHTML:f.sanitizeHTML(a.label)},b);this.own(k(b,
"click",e.hitch(this,function(){this._closeDropMenu();this.openedId?this._switchNodeToClose(this.openedId).then(e.hitch(this,function(){this._showIconContent(b.config)})):this._showIconContent(b.config)})));b.config=a;return b},_setDropMenuPosition:function(a){var b={},b=c.getMarginBox(this.dropMenuNode),b=this._getDropdownPosition(a,b);b.zIndex=101;c.setStyle(this.dropMenuNode,f.getPositionStyle(b))},_getDropdownPosition:function(a,b){var d={};a=c.getMarginBox(a);var e=c.getMarginBox(this.domNode);
d.top=this.height+1;window.isRTL?d.right=0>a.l+a.w-b.w?0:a.l+a.w-b.w:a.l+b.w>e.w?d.right=0:d.left=a.l;return d},_switchNodeToOpen:function(a){a=this._getIconNodeById(a);g(".icon-node",this.domNode).removeClass("jimu-state-selected");c.addClass(a,"jimu-state-selected");console.log(a.config);this._showIconContent(a.config)},_switchNodeToClose:function(a){g(".icon-node",this.domNode).removeClass("jimu-state-selected");var b=this.appConfig.getConfigElementById(a);if(b)return!1===b.inPanel?(this.widgetManager.closeWidget(a),
this.openedId="",a=new p,a.resolve(),a):this.panelManager.closePanel(a+"_panel");a=new p;a.resolve();return a},_getIconNodeById:function(a){a=g('.icon-node[settingId\x3d"'+a+'"]',this.domNode);if(0!==a.length)return a[0]},_unSelectIcon:function(a){g('.icon-node[settingId\x3d"'+a+'"]',this.domNode).removeClass("jimu-state-selected");this.openedId=""},_showIconContent:function(a){!1===a.inPanel?this.widgetManager.loadWidget(a).then(e.hitch(this,function(b){this.openedId=a.id;var d=this._getIconNodeById(a.id);
c.setStyle(b.domNode,"zIndex",101);this._setOffPanelWidgetPosition(d,b);this.widgetManager.openWidget(b);this.own(m.after(b,"onClose",e.hitch(this,function(){this._unSelectIcon(a.id)})))})):this.panelManager.showPanel(a).then(e.hitch(this,function(b){this.openedId=a.id;this.own(m.after(b,"onClose",e.hitch(this,function(){this._unSelectIcon(a.id)})))}))},_setOffPanelWidgetPosition:function(a,b){a=this._getDropdownPosition(a,this.widgetManager.getWidgetMarginBox(b));b.setPosition(a,this.containerNode)},
_showMorePane:function(){var a,b,d=[],f=this.getAllConfigs();for(a=this.headerIconCount;a<f.length;a++)b=f[a],d.push(b);this.morePane&&this.morePane.destroy();this.moreIconPaneCoverNode&&c.destroy(this.moreIconPaneCoverNode);this._closeDropMenu();this.morePane=new A({openedId:this.openedId,items:d});this._createCoverNode();c.place(this.morePane.domNode,jimuConfig.mapId);this.morePane.startup();m.after(this.morePane,"onNodeClicked",e.hitch(this,function(a){this._moveConfigToHeader(a.config);this._createIconNodes(c.getContentBox(this.domNode));
this._onIconClick(this._getIconNodeById(a.config.id))}),!0);m.after(this.morePane,"hide",e.hitch(this,function(){c.destroy(this.moreIconPaneCoverNode)}),!0)},_moveConfigToHeader:function(a){var b=this.getAllConfigs(),c=a.index;a.index=b[this.headerIconCount-1].index;b[this.headerIconCount-1].index=c},_createCoverNode:function(){this.moreIconPaneCoverNode=c.create("div",{"class":"jimu-more-icon-cover"},jimuConfig.layoutId)}})});