//>>built
define({"widgets/AddData/nls/strings":{_widgetLabel:"Add Data",noOptionsConfigured:"No options were configured.",tabs:{search:"Search",url:"URL",file:"File"},search:{featureLayerTitlePattern:"{serviceName} - {layerName}",layerInaccessible:"The layer is inaccessible.",loadError:"AddData, unable to load:",searchBox:{search:"Search",placeholder:"Search..."},bboxOption:{bbox:"Within map"},scopeOptions:{anonymousContent:"Content",myContent:"My Content",myOrganization:"My Organization",curated:"Curated",
ArcGISOnline:"ArcGIS Online"},sortOptions:{prompt:"Sort By:",relevance:"Relevance",title:"Title",owner:"Owner",rating:"Rating",views:"Views",date:"Date",switchOrder:"Switch"},typeOptions:{prompt:"Type",mapService:"Map Service",featureService:"Feature Service",imageService:"Image Service",vectorTileService:"Vector Tile Service",kml:"KML",wms:"WMS"},resultsPane:{noMatch:"No results were found."},paging:{first:"\x3c\x3c",firstTip:"First",previous:"\x3c",previousTip:"Previous",next:"\x3e",nextTip:"Next",
pagePattern:"{page}"},resultCount:{countPattern:"{count} {type}",itemSingular:"Item",itemPlural:"Items"},item:{actions:{add:"Add",close:"Close",remove:"Remove",details:"Details",done:"Done",editName:"Edit Name"},messages:{adding:"Adding...",removing:"Removing...",added:"Added",addFailed:"Add failed",unsupported:"Unsupported"},typeByOwnerPattern:"{type} by {owner}",dateFormat:"MMMM d, yyyy",datePattern:"{date}",ratingsCommentsViewsPattern:"{ratings} {ratingsIcon} {comments} {commentsIcon} {views} {viewsIcon}",
ratingsCommentsViewsLabels:{ratings:"ratings",comments:"comments",views:"views"},types:{"Map Service":"Map Service","Feature Service":"Feature Service","Image Service":"Image Service","Vector Tile Service":"Vector Tile Service",WMS:"WMS",KML:"KML"}}},addFromUrl:{type:"Type",url:"URL",types:{ArcGIS:"An ArcGIS Server Web Service",WMS:"A WMS OGC Web Service",WMTS:"A WMTS OGC Web Service",WFS:"A WFS OGC Web Service",KML:"A KML File",GeoRSS:"A GeoRSS File",CSV:"A CSV File"},samplesHint:"Sample URL(s)"},
addFromFile:{intro:"You can drop or browse for one the following file types:",types:{Shapefile:"A Shapefile (.zip, ZIP archive containing all shapefile files)",CSV:"A CSV File (.csv, with address or latitude, longitude and comma, semi-colon or tab delimited)",KML:"A KML File (.kml)",GPX:"A GPX File (.gpx, GPS Exchange Format)",GeoJSON:"A GeoJSON File (.geo.json or .geojson)"},generalizeOn:"Generalize features for web display",dropOrBrowse:"Drop or Browse",browse:"Browse",invalidType:"This file type is not supported.",
addingPattern:"{filename}: adding...",addFailedPattern:"{filename}: add failed",featureCountPattern:"{filename}: {count} feature(s)",invalidTypePattern:"{filename}: this type is not supported",maxFeaturesAllowedPattern:"A maximum of {count} features is allowed",layerNamePattern:"{filename} - {name}",generalIssue:"There was an issue.",kmlProjectionMismatch:"The spatial reference of the map and KML layer do not match, and the conversion cannot be done on the client."},layerList:{caption:"Layers",noLayersAdded:"No layers have been added.",
removeLayer:"Remove Layer",back:"Back"},_localized:{}},"widgets/Legend/nls/strings":{_widgetLabel:"Legend",_localized:{}},"widgets/LayerList/nls/strings":{_widgetLabel:"Layer List",titleBasemap:"Basemaps",titleLayers:"Operational layers",labelLayer:"Layer name",itemZoomTo:"Zoom to",itemTransparency:"Transparency",itemSetVisibilityRange:"Set visibility range",itemTransparent:"Transparent",itemOpaque:"Opaque",itemMoveUp:"Move up",itemMoveDown:"Move down",itemDesc:"Description",itemDownload:"Download",
itemToAttributeTable:"View in Attribute Table",itemShowItemDetails:"Show item details",empty:"empty",removePopup:"Disable pop-up",enablePopup:"Enable pop-up",turnAllLayersOff:"Turn all layers off",turnAllLayersOn:"Turn all layers on",expandAllLayers:"Expand all layers",collapseAlllayers:"Collapse all layers",turnAllLabelsOff:"Turn all labels off",turnAllLabelsOn:"Turn all labels on",showLabels:"Show labels",hideLables:"Hide labels",keyword:"Keyword",basemapLayers:"Basemap layers",typeAKeywork:"Type a keyword",
layers:"Layers",_localized:{}},"widgets/BasemapGallery/nls/strings":{_widgetLabel:"Basemap Gallery",chooseWebScene:"Choose web scene",chooseWebMap:"Choose web map",_localized:{}},"widgets/Measurement/nls/strings":{_widgetLabel:"Measurement",_localized:{}},"widgets/Geoprocessing/nls/strings":{_widgetLabel:"Geoprocessing",_featureAction_ReceiveFeatureSet:"Set as input of ",requiredInfo:"is required.",drawnOnMap:"The result is drawn on the map.",noToolConfig:"No preconfigured geoprocessing task available.",
useUrlForGPInput:"URL",useUploadForGPInput:"Upload file",selectFileToUpload:"Select file...",rasterFormat:"Raster data format",noFileSelected:"No file selected!",uploadSuccess:"File upload success!",showLayerContent:"Show layer content",invalidUrl:"Invalid feature service url",urlPlaceholder:"URL to access the data",addShapefile:"Add Shapefile",generateShapefileError:"Generate shapefile error, please check: ",cleared:"The result has been cleared.",enlargeView:"Enlarge view",exportOutput:"Export",
emptyResult:"The result is empty.",useSelectedFeatureset:"Use the resultant feature(s).",closeSelectedFeatureset:"Clear and use the configured input opion.",currentMapExtent:"Current map extent",generalize:"Generalize geometries",jsonPlaceholder:"JSON string of the data",chooseATable:"---Select a table---",_localized:{}},"widgets/Bookmark/nls/strings":{labelBookmarkName:"Bookmark the current view",labelPlay:"Play all",labelStop:"Stop",labelDelete:"Delete",placeholderBookmarkName:"Bookmark name",errorNameExist:"Bookmark exists!",
errorNameNull:"Invalid bookmark name!",editTip:"Edit bookmarks",exitEditTip:"Exit editing mode",syncTip:"Synchronize",cardsTips:"Grid view",listTips:"List view",addBtn:"Add",deleteBtn:"Delete",changeThumbnailTip:"Change thumbnail",dragReorderTip:"Hold and drag to reorder",deleteBtnTip:"Delete the bookmark",editBtnTip:"Edit the bookmark",withVisibility:"With layer visibility",searchBookmark:"Search",bookmarksFromConfig:"Preconfigured bookmarks",bookmarksFromCache:"Local temporary bookmarks",notice:"Notice",
changeNoticeTips:"Changes will be saved only in your browser\u2019s cache. Sync between the widget and its configuration is disconnected once you make modifications.",syncNoticeTips:"This will erase all your modifications and restore the configured bookmarks.",dontShowAgain:"Don\u2019t show again",saveVisibility:"Save layer visibility",_widgetLabel:"Bookmark",_localized:{}},"widgets/About/nls/strings":{productVersion:"Product version: ",kernelVersion:"Kernel version: ",_widgetLabel:"About",_localized:{}}});