//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Kokkuvolditav kujundus",_layout_default:"Vaikimisi paigutus",_layout_layout1:"Paigutus 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"P\u00e4ise kontroller",signin:"Logi sisse",signout:"Logi v\u00e4lja",about:"Info",signInTo:"Logi sisse",cantSignOutTip:"See funktsioon pole eelvaatere\u017eiimis rakendatav.",more:"rohkem",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"M\u00f5\u00f5tkava",
_localized:{}},"esri/layers/vectorTiles/nls/common":{_localized:{}},"widgets/Search/nls/strings":{_widgetLabel:"Otsi",searchResult:"Otsi tulemusi",showAllResults:"N\u00e4ita otsingutulemusi p\u00e4ringule ",showAll:"N\u00e4ita otsingutulemusi",more:"rohkem",untitled:"Pealkirjata",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Koordinaat",hintMessage:"Klikkige koordinaatide hankimiseks kaardile",defaultLabel:"Vaikimisi",realtimeLabel:"Koordinaatide hankimiseks liigutage kursorit",computing:"Arvutamine...",
latitudeLabel:"Laius",longitudeLabel:"Pikkus",loading:"laadimine...",enableClick:"Klikkige, et lubada klikkimise kaudu kaardilt koordinaate hankida",disableClick:"Klikkige, et keelata klikkimise kaudu kaardilt koordinaate hankida",Default:"Vaikimisi",Inches:"tolli",Foot:"Jalga",Foot_US:"Feet_US",Yards:"jardi",Miles:"miili",Nautical_Miles:"Meremiili",Millimeters:"millimeeter",Centimeters:"sentimeetrit",Meter:"Meetrit",Kilometers:"kilomeetrit",Decimeters:"detsimeetrit",Decimal_Degrees:"Kraadi",Degree_Minutes_Seconds:"Kraadid minutid sekundid",
MGRS:"MGRS",USNG:"USNG",_localized:{}},"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"At least one item must be selected.",multiSelectLabelText:"{num} item(s) selected",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"V\u00f5rdlus",swipeText:" Valige rullimise abil v\u00f5rreldavad kihid",spyglassText:"Valige pikksilmas kuvatav kiht.",disableTips:"Kl\u00f5psake v\u00f5rdleva rullimist\u00f6\u00f6riista keelamiseks.",enableTips:"Kl\u00f5psake v\u00f5rdleva rullimist\u00f6\u00f6riista lubamiseks.",
defaultLayerHolder:"Kl\u00f5psake valimiseks",selectLayers:"Vali kihid",nItemsSelected:"Kiht (kihid) valitud",showList:"Kuva kihtide loend",hideList:"Peida kihtide loend",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Ajaliugur",enableTips:"Kl\u00f5psake ajaliuguri kuvamiseks.",disableTips:"Ajateadlikke kihte pole n\u00e4htaval.",timeExtent:"${FROMTIME} kuni ${ENDTIME}",layers:"Kihid: ",speedLabel:"Esituse kiirus",liveData:"Reaalajas andmed",_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"\u00dclevaatekaart",
_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Avaleht",_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"Minu asukoht",title:"Leia minu asukoht",browserError:"See brauser ei toeta asukoha m\u00e4\u00e4ramist.",failureFinding:"Teie asukohta ei \u00f5nnestu leida. Kontrollige brauseri kaudu, kas Teie asukoht on jagatud.",httpNotSupportError:"See vidin on saadaval ainult siis, kui rakendusele juurdep\u00e4\u00e4semiseks kasutatakse brauseri protokolli HTTPS.",_localized:{}},
"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Kuva v\u00f5i peida veerud",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Atribuuttabel",_featureAction_ShowRelatedRecords:"Kuva seotud kirjed",_featureAction_ViewInTable:"Vaata atribuuttabelis",ok:"OK",cancel:"T\u00fchista",unsupportQueryWarning:"Kiht peab toetama p\u00e4ringut, et seda kuvataks atribuuditabeli vidinas. Veenduge, et p\u00e4ringufunktsioon oleks teenuses sisse l\u00fclitatud.",
exportMessage:"Kas soovite eksportida andmed CSV faili?",exportFiles:"Ekspordi CSV faili",exportSelected:"Ekspordi valitud osa CSV formaati",exportAll:"Ekspordi k\u00f5ik CSV formaati",options:"Valikud",zoomto:"Suumi",highlight:"T\u00f5sta graafika esile",selectAll:"Vali k\u00f5igi lehtede kirjed",selectPage:"Vali praeguse lehe kirjed",clearSelection:"Puhasta valik",filter:"Filter",setFilterTip:"M\u00e4\u00e4rake filtrid \u00f5igesti.",noFilterTip:"M\u00e4\u00e4ratlemata filtriavaldiseta loendab see p\u00e4ringu\u00fclesanne k\u00f5ik m\u00e4\u00e4ratud andmeallika funktsioonid.",
filterByExtent:"Filtreeri kaardi ulatuse j\u00e4rgi",showSelectedRecords:"N\u00e4ita valitud kirjeid",showAllRecords:"N\u00e4ita k\u00f5iki kirjeid",showRelatedRecords:"Kuva seotud kirjed",noRelatedRecords:"Seotud kirjeid ei leitud",highlightAllRecords:"T\u00f5sta k\u00f5ik kirjed kaardil esile",attachmentColumn:"Fotod ja failid",refresh:"V\u00e4rskenda",features:"objektid",records:"kirjed",selected:"valitud",transparent:"L\u00e4bipaistvuse re\u017eiim",indicate:"Paiguta valitu",columns:"Kuva/peida veerud",
selectionSymbol:"Valiku s\u00fcmbol",closeMessage:"Peida tabel (laienda seda uuesti altpoolt)",dataNotAvailable:"Andmed ei ole saadaval!\x3cbr\x3eUuesti proovimiseks klikkige nuppu [V\u00e4rskenda]",openTableTip:"Ava atribuuttabel",closeTableTip:"Peida atribuuttabel",sortAsc:"Sorteeri kasvavalt",sortDes:"Sorteeri kahanevalt",statistics:"Statistika",attachments:"Manused",files:"failid",keepRichTextLabel:"S\u00e4ilita rikasteksti formaat",whatsThis:"Mis see on?",richTextMessage:{explanatoryText:{line1:"${layerName} sisaldab j\u00e4rgmisi rikastekstiv\u00e4lju: ",
line2:" ja need v\u00f5ivad sisaldada teksti vormindamise laade (nt font, v\u00e4rv, tekstisuurus).",line3:"CSV-faili eksportimisel s\u00e4ilitatakse vorminduslaadid HTML-m\u00e4rgendite abil. Kui Te ei soovi rikasteksti formaate s\u00e4ilitada, t\u00fchjendage ruut \u201eS\u00e4ilita rikasteksti formaat\u201c."},example:{label:"N\u00e4ited.",scenarios:{first:"eksporditakse vaikimisi j\u00e4rgmise tekstina:",second:"ja j\u00e4rgmine tekst rikasteksti formaadita:"}}},noTablesAvailable:"Puuduvad tabelid, mida kuvada.",
checkConfigutationToSelectLayers:"Kihtide valimiseks minge vidina seadete lehele.",checkLayerListToSelectLayers:"Atribuuditabel s\u00fcnkroniseeritakse kaardil n\u00e4htavate kihtidega. Kihtide sisse- v\u00f5i v\u00e4ljal\u00fclitamiseks saate kasutada n\u00e4iteks kihiloendi vidinat.",_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Suumimise liugur",_localized:{}}});