//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Temaet Foldbar",_layout_default:"Standardoppsett",_layout_layout1:"Oppsett 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"Hodekontroller",signin:"Logg p\u00e5",signout:"Logg av",about:"Om",signInTo:"Logg inn p\u00e5",cantSignOutTip:"Denne funksjonen er ikke relevant i forh\u00e5ndsvisningsmodus.",more:"mer",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"m\u00e5lestokklinjal",_localized:{}},
"esri/layers/vectorTiles/nls/common":{_localized:{}},"widgets/Search/nls/strings":{_widgetLabel:"S\u00f8ke",searchResult:"S\u00f8keresultater",showAllResults:"Vis s\u00f8keresultater for ",showAll:"Vis s\u00f8keresultater",more:"mer",untitled:"Uten tittel",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Koordinat",hintMessage:"Klikk p\u00e5 kartet for \u00e5 f\u00e5 koordinater",defaultLabel:"Standard",realtimeLabel:"Beveg musen for \u00e5 f\u00e5 koordinater",computing:"Behandler...",
latitudeLabel:"Breddegrad",longitudeLabel:"Lengdegrad",loading:"laster inn...",enableClick:"Klikk for \u00e5 aktivere funksjonen for \u00e5 klikke p\u00e5 kartet for \u00e5 f\u00e5 koordinater",disableClick:"Klikk for \u00e5 deaktivere funksjonen for \u00e5 klikke p\u00e5 kartet for \u00e5 f\u00e5 koordinater",Default:"Standard",Inches:"Tommer",Foot:"Fot",Foot_US:"Feet_US",Yards:"Yards",Miles:"Miles",Nautical_Miles:"Nautiske mil",Millimeters:"Millimeter",Centimeters:"Centimeter",Meter:"Meter",Kilometers:"Kilometer",
Decimeters:"Desimeter",Decimal_Degrees:"Grader",Degree_Minutes_Seconds:"Grader minutter sekunder",MGRS:"MGRS",USNG:"USNG",_localized:{}},"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"Du m\u00e5 velge minst ett element.",multiSelectLabelText:"{num} element(er) valgt",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"Sveiping",swipeText:" Velg laget/lagene du vil sveipe",spyglassText:"Velg laget som skal vises i kikkerten",disableTips:"Klikk for \u00e5 deaktivere sveipeverkt\u00f8yet",
enableTips:"Klikk for \u00e5 aktivere sveipeverkt\u00f8yet",defaultLayerHolder:"Klikk for \u00e5 velge",selectLayers:"Velg lag",nItemsSelected:"lag er valgt",showList:"vis lagliste",hideList:"skjul lagliste",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Tidspanorerer",enableTips:"Klikk for \u00e5 vise knapp for tidspanorering.",disableTips:"Ingen tidsbevisste lag er synlige.",timeExtent:"${FROMTIME} til ${ENDTIME}",layers:"Lag: ",speedLabel:"Avspillingshastighet",liveData:"Aktive data",
_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"Oversiktskart",_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Hjem",_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"Min lokasjon",title:"Finn min lokasjon",browserError:"Geolokasjon st\u00f8ttes ikke av denne nettleseren.",failureFinding:"Kan ikke finne lokasjonen din. Kontroller webleseren din for \u00e5 sikre at lokasjonen din deles.",httpNotSupportError:"Dette miniprogrammet er bare tilgjengelig n\u00e5r appen \u00e5pnes gjennom HTTPS i denne nettleseren.",
_localized:{}},"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Vis eller skjul kolonner",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Attributtabell",_featureAction_ShowRelatedRecords:"Vis relaterte poster",_featureAction_ViewInTable:"Vis i attributtabell",ok:"OK",cancel:"Avbryt",unsupportQueryWarning:"Laget m\u00e5 st\u00f8tte sp\u00f8rringsoperasjoner for \u00e5 kunne vises i attributtabell-widget. S\u00f8rg for at sp\u00f8rringsfunksjonen i tjenesten er sl\u00e5tt p\u00e5.",
exportMessage:"Eksportere data til CSV-fil?",exportFiles:"Eksporter til CSV",exportSelected:"Eksporter utvalg til CSV",exportAll:"Eksporter alt til CSV",options:"Alternativer",zoomto:"Zoom til",highlight:"Uthev grafikk",selectAll:"Velg poster p\u00e5 alle sider",selectPage:"Velg poster p\u00e5 gjeldende side",clearSelection:"T\u00f8m utvalg",filter:"Filter",setFilterTip:"Angi filtre p\u00e5 riktig m\u00e5te.",noFilterTip:"Uten definerte filteruttrykk viser denne sp\u00f8rringoppgaven alle geoobjekter i den angitte datakilden.",
filterByExtent:"Filtrer etter kartutstrekning",showSelectedRecords:"Vis valgte poster",showAllRecords:"Vis alle poster",showRelatedRecords:"Vis relaterte poster",noRelatedRecords:"Ingen tilknyttede oppf\u00f8ringer funnet",highlightAllRecords:"Uthev alle poster p\u00e5 kartet",attachmentColumn:"Bilder og filer",refresh:"Oppdater",features:"geoobjekter",records:"poster",selected:"valgte",transparent:"Gjennomsiktig modus",indicate:"Finn utvalg",columns:"Vis/skjul kolonner",selectionSymbol:"Utvalgsymbol",
closeMessage:"Skjul tabell (utvid den igjen fra bunnen)",dataNotAvailable:"Data ikke tilgjengelig!\x3cbr\x3eKlikk p\u00e5 [Oppdater] for \u00e5 pr\u00f8ve p\u00e5 nytt.",openTableTip:"\u00c5pne attributtabell",closeTableTip:"Skjul attributt-tabell",sortAsc:"Sorter stigende",sortDes:"Sorter synkende",statistics:"Statistikk",attachments:"Vedlegg",files:"filer",keepRichTextLabel:"Behold rikt tekstformat",whatsThis:"Hva er dette?",richTextMessage:{explanatoryText:{line1:"${layerName} inneholder f\u00f8lgende felt(er) for rik tekst: ",
line2:" som kan inneholde stiler for tekstformatering, som skrifttyper, farger eller tekstst\u00f8rrelser.",line3:"N\u00e5r de eksporteres til CSV, bevares formateringsstilene i form av HTML-koder. Du kan velge ikke \u00e5 beholde rik tekstformatene ved \u00e5 fjerne avmerkingen av boksen \u00abBehold rikt tekstformat\u00bb."},example:{label:"Eksempel:",scenarios:{first:"blir som standard eksportert som f\u00f8lgende tekst:",second:"og f\u00f8lgende tekst uten rikt tekstformat:"}}},noTablesAvailable:"Ingen tabeller tilgjengelig for visning.",
checkConfigutationToSelectLayers:"G\u00e5 til siden for miniprograminnstillinger for \u00e5 velge lag.",checkLayerListToSelectLayers:"Attributtabellen er synkronisert med synlige lag i kartet; du kan bruke et miniprogram som Lagliste for \u00e5 aktivere/deaktivere lag.",_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Zoom-glidebryter",_localized:{}}});