//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Foldable-Design",_layout_default:"Standard-Layout",_layout_layout1:"Layout 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"Header-Controller",signin:"Anmelden",signout:"Abmelden",about:"Info",signInTo:"Melden Sie sich an bei",cantSignOutTip:"Diese Funktion ist im Vorschaumodus nicht zutreffend.",more:"mehr",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"Ma\u00dfstabsleiste",_localized:{}},
"esri/layers/vectorTiles/nls/common":{_localized:{}},"widgets/Search/nls/strings":{_widgetLabel:"Suche",searchResult:"Suchergebnis",showAllResults:"Suchergebnisse anzeigen f\u00fcr ",showAll:"Suchergebnisse anzeigen",more:"mehr",untitled:"Ohne Titel",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Koordinaten",hintMessage:"Zum Abrufen von Koordinaten auf die Karte klicken",defaultLabel:"Standard",realtimeLabel:"Maus zum Abrufen von Koordinaten auf der Karte bewegen",computing:"Wird berechnet...",
latitudeLabel:"Breitengrad",longitudeLabel:"L\u00e4ngengrad",loading:"wird geladen...",enableClick:"Klicken Sie, um das Abrufen von Koordinaten durch Klicken auf die Karte zu aktivieren",disableClick:"Klicken Sie, um das Abrufen von Koordinaten durch Klicken auf die Karte zu deaktivieren",Default:"Standard",Inches:"Zoll",Foot:"Fu\u00df",Foot_US:"Feet_US",Yards:"Yard",Miles:"Meilen",Nautical_Miles:"Seemeilen",Millimeters:"Millimeter",Centimeters:"Zentimeter",Meter:"Meter",Kilometers:"Kilometer",Decimeters:"Dezimeter",
Decimal_Degrees:"Grad",Degree_Minutes_Seconds:"Grad, Minuten, Sekunden",MGRS:"MGRS",USNG:"USNG",_localized:{}},"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"Es muss mindestens ein Eintrag ausgew\u00e4hlt werden.",multiSelectLabelText:"{num} Eintrag/Eintr\u00e4ge ausgew\u00e4hlt",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"Vergleichen",swipeText:" W\u00e4hlen Sie die Layer aus, die ausgeblendet werden sollen.",spyglassText:"W\u00e4hlen Sie den Layer aus, der im Fernglas angezeigt werden soll",
disableTips:'Zum Deaktivieren des Werkzeugs "Vergleichen" deaktivieren',enableTips:'Zum Aktivieren des Werkzeugs "Vergleichen" klicken',defaultLayerHolder:"Zum Ausw\u00e4hlen klicken",selectLayers:"Layer ausw\u00e4hlen",nItemsSelected:"Layer ausgew\u00e4hlt",showList:"Layer-Liste anzeigen",hideList:"Layer-Liste ausblenden",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Zeitschieberegler",enableTips:"Klicken Sie hier, um den Zeitschieberegler anzuzeigen.",disableTips:"Es sind keine zeitbezogenen Layer sichtbar.",
timeExtent:"${FROMTIME} bis ${ENDTIME}",layers:"Layer: ",speedLabel:"Wiedergabegeschwindigkeit",liveData:"Live-Daten",_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"\u00dcbersichtskarte",_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Standardausdehnung",_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"Eigene Position",title:"Eigenen Standort suchen",browserError:"Geolocation wird von diesem Browser nicht unterst\u00fctzt.",failureFinding:"Ihre Position kann nicht gefunden werden. \u00dcberpr\u00fcfen Sie Ihren Browser, um sicherzustellen, dass Ihre Position freigegeben wurde.",
httpNotSupportError:"Das Widget ist nur dann verf\u00fcgbar, wenn die App in diesem Browser \u00fcber HTTPS aufgerufen wird.",_localized:{}},"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Spalten ein- oder ausblenden",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Attributtabelle",_featureAction_ShowRelatedRecords:"Zugeh\u00f6rige Datens\u00e4tze anzeigen",_featureAction_ViewInTable:"In Attributtabelle anzeigen",ok:"OK",cancel:"Abbrechen",
unsupportQueryWarning:"Der Layer muss die Abfrageoperation unterst\u00fctzen, um im Widget der Attributtabelle angezeigt zu werden. Stellen Sie sicher, dass die Abfragefunktion in dem Service aktiviert ist.",exportMessage:"Daten in CSV-Datei exportieren?",exportFiles:"In CSV exportieren",exportSelected:"Ausgew\u00e4hlte Elemente in CSV exportieren",exportAll:"Alle Elemente in CSV exportieren",options:"Optionen",zoomto:"Zoomen auf",highlight:"Grafiken hervorheben",selectAll:"Datens\u00e4tze auf allen Seiten ausw\u00e4hlen",
selectPage:"Datens\u00e4tze auf aktueller Seite ausw\u00e4hlen",clearSelection:"Auswahl aufheben",filter:"Filter",setFilterTip:"Legen Sie die Filter ordnungsgem\u00e4\u00df fest.",noFilterTip:"Dieser Abfrage-Task listet alle Features in der angegebenen Datenquelle ohne definierten Filterausdruck auf.",filterByExtent:"Nach Kartenausdehnung filtern",showSelectedRecords:"Ausgew\u00e4hlte Datens\u00e4tze anzeigen",showAllRecords:"Alle Datens\u00e4tze anzeigen",showRelatedRecords:"Zugeh\u00f6rige Datens\u00e4tze anzeigen",
noRelatedRecords:"Keine zugeh\u00f6rigen Datens\u00e4tze gefunden",highlightAllRecords:"Alle Datens\u00e4tze auf der Karte hervorheben",attachmentColumn:"Fotos und Dateien",refresh:"Aktualisieren",features:"Features",records:"Datens\u00e4tze",selected:"ausgew\u00e4hlt",transparent:"Transparentmodus",indicate:"Auswahl suchen",columns:"Spalten ein-/ausblenden",selectionSymbol:"Auswahlsymbol",closeMessage:"Tabelle ausblenden (von unten wieder einblenden)",dataNotAvailable:"Daten nicht verf\u00fcgbar!\x3cbr\x3eKlicken Sie auf die Schaltfl\u00e4che [Aktualisieren], um es erneut zu versuchen.",
openTableTip:"Attributtabelle \u00f6ffnen",closeTableTip:"Attributtabelle ausblenden",sortAsc:"Aufsteigend sortieren",sortDes:"Absteigend sortieren",statistics:"Statistiken",attachments:"Anlagen",files:"Dateien",keepRichTextLabel:"Rich Text Format beibehalten",whatsThis:"Erfahren Sie mehr",richTextMessage:{explanatoryText:{line1:"${layerName} enth\u00e4lt das bzw. die folgende(n) Rich-Text-Feld(er): ",line2:" Darin k\u00f6nnen Textformatierungs-Styles wie Schriftarten, Farben oder Textgr\u00f6\u00dfen enthalten sein.",
line3:'Beim Exportieren in eine CSV-Datei werden die Formatierungs-Styles in Form von HTML-Tags beibehalten. Wenn Sie das Rich Text Format nicht beibehalten m\u00f6chten, deaktivieren Sie das Kontrollk\u00e4stchen "Rich Text Format beibehalten".'},example:{label:"Beispiel:",scenarios:{first:"wird standardm\u00e4\u00dfig als folgender Text exportiert:",second:"und ohne Rich Text Format als folgender Text:"}}},noTablesAvailable:"Es sind keine Tabellen f\u00fcr die Anzeige verf\u00fcgbar.",checkConfigutationToSelectLayers:"Wechseln Sie zur Einstellungsseite, um Layer auszuw\u00e4hlen.",
checkLayerListToSelectLayers:'Die Attributtabelle wurde mit den sichtbaren Layern in der Karte synchronisiert. Mit Widgets wie "Layer-Liste" k\u00f6nnen Sie Layer aktivieren oder deaktivieren.',_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Zoom-Schieberegler",_localized:{}}});