//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Vikbart tema",_layout_default:"Standardlayout",_layout_layout1:"Layout 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"Rubrikhanterare",signin:"N\u00e4stan klar",signout:"kvarvarande",about:"Om",signInTo:"Logga in p\u00e5",cantSignOutTip:"Denna funktion \u00e4r inte tillg\u00e4nglig i f\u00f6rhandsgranskningsl\u00e4ge.",more:"fler",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"Skalf\u00e4lt",
_localized:{}},"esri/layers/vectorTiles/nls/common":{_localized:{}},"widgets/Search/nls/strings":{_widgetLabel:"S\u00f6k",searchResult:"S\u00f6kresultat",showAllResults:"Visa s\u00f6kresultat f\u00f6r ",showAll:"Visa s\u00f6kresultat",more:"fler",untitled:"Namnl\u00f6s",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Koordinat",hintMessage:"Klicka p\u00e5 kartan f\u00f6r att h\u00e4mta koordinater",defaultLabel:"Standard",realtimeLabel:"Flytta musen f\u00f6r att h\u00e4mta koordinater",
computing:"Ber\u00e4knar ...",latitudeLabel:"Latitud",longitudeLabel:"Longitud",loading:"l\u00e4ser in...",enableClick:"Klicka om du vill aktivera att f\u00e5 koordinater genom att klicka p\u00e5 kartan",disableClick:"Klicka om du vill inaktivera att f\u00e5 koordinater genom att klicka p\u00e5 kartan",Default:"Standard",Inches:"Tum",Foot:"Fot",Foot_US:"Fot_US",Yards:"Yard",Miles:"Engelska mil",Nautical_Miles:"Nautiska mil",Millimeters:"Millimeter",Centimeters:"Centimeter",Meter:"Meter",Kilometers:"Kilometer",
Decimeters:"Decimeter",Decimal_Degrees:"Grader",Degree_Minutes_Seconds:"Grader minuter sekunder",MGRS:"MGRS",USNG:"USNG",_localized:{}},"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"Du m\u00e5ste v\u00e4lja minst ett objekt.",multiSelectLabelText:"{num} objekt har valts",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"Svep",swipeText:" V\u00e4lj de lager som ska svepas",spyglassText:"V\u00e4lj det lager som ska visas i kikaren",disableTips:"Klicka om du vill inaktivera svepverktyget",
enableTips:"Klicka om du vill aktivera svepverktyget",defaultLayerHolder:"Klicka f\u00f6r att v\u00e4lja",selectLayers:"V\u00e4lj lager",nItemsSelected:"lager har markerats",showList:"visa lagerlista",hideList:"d\u00f6lj lagerlista",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Tidsreglage",enableTips:"Klicka f\u00f6r att visa tidsreglaget.",disableTips:"Inga tidsk\u00e4nsliga lager \u00e4r synliga.",timeExtent:"${FROMTIME} till ${ENDTIME}",layers:"Lager: ",speedLabel:"Uppspelningshastighet",
liveData:"Realtidsdata",_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"\u00d6versiktskarta",_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Hem",_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"Min plats",title:"Hitta min plats",browserError:"Den h\u00e4r webbl\u00e4saren har inte st\u00f6d f\u00f6r geolokalisering.",failureFinding:"Det g\u00e5r inte att hitta din plats. Kontrollera i webbl\u00e4saren att platsen \u00e4r delad.",httpNotSupportError:"Den h\u00e4r widgeten \u00e4r bara tillg\u00e4nglig n\u00e4r appen \u00f6ppnas via HTTPS i denna webbl\u00e4sare.",
_localized:{}},"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Visa eller d\u00f6lj kolumner",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Attributtabell",_featureAction_ShowRelatedRecords:"Visa relaterade poster",_featureAction_ViewInTable:"Visa i attributtabell",ok:"OK",cancel:"Avbryt",unsupportQueryWarning:"Lagret m\u00e5ste ha st\u00f6d f\u00f6r fr\u00e5ge\u00e5tg\u00e4rden f\u00f6r att visas i widgeten Attributtabell. Kontrollera att fr\u00e5gefunktionen i tj\u00e4nsten \u00e4r p\u00e5slagen.",
exportMessage:"Exportera data till CSV-fil?",exportFiles:"Exportera till CSV",exportSelected:"Exportera vald till CSV",exportAll:"Exportera allt till CSV",options:"Alternativ",zoomto:"Zooma till",highlight:"Markera grafik",selectAll:"V\u00e4lj poster p\u00e5 alla sidor",selectPage:"V\u00e4lj poster p\u00e5 aktuell sida",clearSelection:"Rensa markering",filter:"Filter",setFilterTip:"Ange filtren korrekt.",noFilterTip:"Om inga filteruttryck definierats visar denna fr\u00e5geuppgift en lista med alla geoobjekt i den angivna datak\u00e4llan.",
filterByExtent:"Filtrera efter kartutbredning",showSelectedRecords:"Visa valda poster",showAllRecords:"Visa alla poster",showRelatedRecords:"Visa relaterade poster",noRelatedRecords:"Inga relaterade poster hittades",highlightAllRecords:"Markera alla poster i kartan",attachmentColumn:"Foton och filer",refresh:"Uppdatera",features:"geoobjekt",records:"posterna",selected:"valt",transparent:"Transparent l\u00e4ge",indicate:"Hitta val",columns:"Visa/d\u00f6lj kolumner",selectionSymbol:"Markeringssymbol",
closeMessage:"D\u00f6lj tabell (expandera den igen fr\u00e5n nederkanten)",dataNotAvailable:"Data \u00e4r inte tillg\u00e4ngliga!\x3cbr\x3eKlicka p\u00e5 [Uppdatera] f\u00f6r att f\u00f6rs\u00f6ka igen.",openTableTip:"\u00d6ppna attributtabell",closeTableTip:"D\u00f6lj attributtabell",sortAsc:"Sortera stigande",sortDes:"Sortera fallande",statistics:"Statistik",attachments:"Bilagor",files:"filer",keepRichTextLabel:"Bevara RTF-format",whatsThis:"Vad \u00e4r detta?",richTextMessage:{explanatoryText:{line1:"${layerName} inneh\u00e5ller f\u00f6ljande RTF-f\u00e4lt: ",
line2:" , som kan inkludera textformatering som typsnitt, f\u00e4rg och textstorlekar.",line3:"Om det exporteras till CSV bevaras formateringen som HTML-taggar. Du kan v\u00e4lja att inte bevara RTF-formateringen genom att avmarkera rutan Bevara RTF-format."},example:{label:"Exempel:",scenarios:{first:"exporteras som standard som f\u00f6ljande text:",second:"och f\u00f6ljande text utan RTF-format:"}}},noTablesAvailable:"Inga tabeller finns att visa.",checkConfigutationToSelectLayers:"G\u00e5 till widgetens inst\u00e4llningssida f\u00f6r att v\u00e4lja lager.",
checkLayerListToSelectLayers:"Attributtabellen synkroniseras med synliga lager i kartan. Du kan anv\u00e4nda en widget som exempelvis Lagerlista f\u00f6r att v\u00e4xla lager av/p\u00e5.",_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Zoomskjutreglage",_localized:{}}});