//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Plegable",_layout_default:"Dise\u00f1o predeterminado",_layout_layout1:"Dise\u00f1o 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"Controlador de encabezado",signin:"Iniciar sesi\u00f3n",signout:"Cerrar sesi\u00f3n",about:"Acerca de",signInTo:"Iniciar sesi\u00f3n en",cantSignOutTip:"Esta funci\u00f3n no est\u00e1 disponible en el modo de vista previa.",more:"m\u00e1s",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"Barra de escala",
_localized:{}},"esri/layers/vectorTiles/nls/common":{_localized:{}},"widgets/Search/nls/strings":{_widgetLabel:"B\u00fasqueda",searchResult:"Resultado de la b\u00fasqueda",showAllResults:"Buscar resultados de ",showAll:"Mostrar resultados de",more:"m\u00e1s",untitled:"Sin T\u00edtulo",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Coordenada",hintMessage:"Haz clic en el mapa para obtener coordenadas",defaultLabel:"Predeterminado",realtimeLabel:"Mover el rat\u00f3n para obtener coordenadas",
computing:"Calculando...",latitudeLabel:"Latitud",longitudeLabel:"Longitud",loading:"cargando...",enableClick:"Haz clic para habilitar la obtenci\u00f3n de coordenadas al hacer clic en el mapa",disableClick:"Haz clic para deshabilitar la obtenci\u00f3n de coordenadas al hacer clic en el mapa",Default:"Predeterminado",Inches:"Pulgadas",Foot:"Pies",Foot_US:"Feet_US",Yards:"Yardas",Miles:"Millas",Nautical_Miles:"Millas n\u00e1uticas",Millimeters:"Mil\u00edmetros",Centimeters:"Cent\u00edmetros",Meter:"Metros",
Kilometers:"Kil\u00f3metros",Decimeters:"Dec\u00edmetros",Decimal_Degrees:"Grados",Degree_Minutes_Seconds:"Grados minutos segundos",MGRS:"MGRS",USNG:"USNG",_localized:{}},"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"Se debe seleccionar al menos un elemento.",multiSelectLabelText:"{num} elemento(s) seleccionado(s)",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"Swipe",swipeText:" Seleccione la(s) capa(s) en las que desee la funci\u00f3n swipe",spyglassText:"Selecciona la capa que debe aparecer en la lupa",
disableTips:"Haz clic para desactivar la herramienta swipe",enableTips:"Haz clic para activar la herramienta de swipe",defaultLayerHolder:"Clic para seleccionar",selectLayers:"Seleccionar capas",nItemsSelected:"capas seleccionadas",showList:"mostrar lista de capas",hideList:"ocultar lista de capas",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Control deslizante de tiempo",enableTips:"Haz clic para mostrar el control deslizante de tiempo.",disableTips:"No hay capas con valores de tiempo visibles.",
timeExtent:"De ${FROMTIME} a ${ENDTIME}",layers:"Capas: ",speedLabel:"Velocidad de reproducci\u00f3n",liveData:"Datos en directo",_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"Mapa de vista general",_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Inicio",_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"Mi ubicaci\u00f3n",title:"Buscar mi ubicaci\u00f3n",browserError:"Este navegador no es compatible con la geolocalizaci\u00f3n.",failureFinding:"No se encuentra tu ubicaci\u00f3n. Comprueba tu navegador para asegurarte de que la ubicaci\u00f3n est\u00e9 compartida.",
httpNotSupportError:"Este widget solo est\u00e1 disponible cuando se accede a la aplicaci\u00f3n mediante HTTPS en este navegador.",_localized:{}},"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Mostrar o esconder columnas",popupLabel:"Mostrar o esconder columnas",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Tabla de atributos",_featureAction_ShowRelatedRecords:"Mostrar registros relacionados",_featureAction_ViewInTable:"Ver en la tabla de atributos",ok:"Aceptar",cancel:"Cancelar",
unsupportQueryWarning:"La capa debe ser compatible con la operaci\u00f3n de consulta para mostrar el widget Tabla de atributos. Aseg\u00farate de que la funci\u00f3n de consulta en el servicio est\u00e1 activada.",exportMessage:"\u00bfExportar datos a archivo CSV?",exportFiles:"Exportar a CSV",exportSelected:"Exportar selecci\u00f3n a CSV",exportAll:"Exportar todo a CSV",options:"Opciones",zoomto:"Acercar a",highlight:"Resaltar gr\u00e1ficos",selectAll:"Seleccionar registros en todas las p\u00e1ginas",
selectPage:"Seleccionar registros en la p\u00e1gina actual",clearSelection:"Borrar selecci\u00f3n",filter:"Filtro",setFilterTip:"Defina los filtros correctamente.",noFilterTip:"Sin expresiones de filtro definidas, esta tarea de consulta mostrar\u00e1 todas las entidades de la fuente de datos especificada.",filterByExtent:"Filtrar por extensi\u00f3n de mapa",showSelectedRecords:"Mostrar registros seleccionados",showAllRecords:"Mostrar todos los registros",showRelatedRecords:"Mostrar registros relacionados",
noRelatedRecords:"No se encontraron registros relacionados",highlightAllRecords:"Resaltar todos los registros del mapa",attachmentColumn:"Fotos y archivos",refresh:"Actualizar",features:"entidades",records:"registros",selected:"seleccionado",transparent:"Modo transparente",indicate:"Localizar selecci\u00f3n",columns:"Mostrar/Ocultar columnas",selectionSymbol:"S\u00edmbolo de selecci\u00f3n",closeMessage:"Ocultar tabla (volver a expandirla desde la parte inferior)",dataNotAvailable:"\u00a1Datos no disponibles!\x3cbr\x3eHaz clic en el bot\u00f3n [Actualizar] para intentarlo de nuevo.",
openTableTip:"Abrir tabla de atributos",closeTableTip:"Ocultar tabla de atributos",sortAsc:"Orden ascendente",sortDes:"Orden descendente",statistics:"Estad\u00edsticas",attachments:"Adjuntos",files:"archivos",keepRichTextLabel:"Conservar formato de texto enriquecido",whatsThis:"\u00bfQu\u00e9 es esto?",richTextMessage:{explanatoryText:{line1:"${layerName} contiene los siguientes campos de texto enriquecido: ",line2:" que podr\u00eda incluir estilos de formato de texto, tales como fuentes, colores o tama\u00f1os de texto.",
line3:'Al exportar a CSV, los estilos de formato se conservan en forma de etiquetas HTML. Usted tiene la opci\u00f3n de no conservar los formatos de texto enriquecido desactivando la casilla "Conservar formato de texto enriquecido".'},example:{label:"Por ejemplo:",scenarios:{first:"se exportar\u00e1 de forma predeterminada como el siguiente texto:",second:"y el siguiente texto sin formato de texto enriquecido:"}}},noTablesAvailable:"No hay tablas disponibles para mostrarlas.",checkConfigutationToSelectLayers:"Vaya a la p\u00e1gina de ajustes de widget para seleccionar las capas.",
checkLayerListToSelectLayers:"La tabla de atributos est\u00e1 sincronizada con capas visibles en el mapa; puede usar un widget, por ejemplo, Lista de capas, para activar/desactivar las capas.",_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Control deslizante de zoom",_localized:{}}});