//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Tema avviluppabile",_layout_default:"Layout predefinito",_layout_layout1:"Layout 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"Controller intestazione",signin:"Accedi",signout:"Disconnetti",about:"Informazioni",signInTo:"Accedi a",cantSignOutTip:"Questa funzione non \u00e8 disponibile in modalit\u00e0 anteprima.",more:"altro",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"Barra della scala",
_localized:{}},"esri/layers/vectorTiles/nls/common":{_localized:{}},"widgets/Search/nls/strings":{_widgetLabel:"Ricerca",searchResult:"Risultato ricerca",showAllResults:"Mostra risultati ricerca per ",showAll:"Mostra risultati ricerca",more:"altro",untitled:"Senza titolo",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Coordinata",hintMessage:"Fare clic sulla mappa per ottenere le coordinate",defaultLabel:"Impostazione predefinita",realtimeLabel:"Spostare il mouse per ottenere le coordinate",
computing:"Calcolo in corso...",latitudeLabel:"Latitudine",longitudeLabel:"Longitudine",loading:"caricamento in corso...",enableClick:"Fare clic per abilitare la generazione delle coordinate mediante il clic sulla mappa",disableClick:"Fare clic per disabilitare la generazione delle coordinate mediante il clic sulla mappa",Default:"Impostazione predefinita",Inches:"Pollici",Foot:"Piedi",Foot_US:"Piedi (USA)",Yards:"Iarde",Miles:"Miglia",Nautical_Miles:"Miglia nautiche",Millimeters:"Millimetri",Centimeters:"Centimetri",
Meter:"Metri",Kilometers:"Chilometri",Decimeters:"Decimetri",Decimal_Degrees:"Gradi",Degree_Minutes_Seconds:"Gradi minuti secondi",MGRS:"MGRS",USNG:"USNG",_localized:{}},"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"\u00c8 necessario selezionare almeno un elemento.",multiSelectLabelText:"{num} elementi selezionati",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"Scorrimento con dito",swipeText:" Selezionare i layer su cui si desidera scorrere il dito",spyglassText:"Selezionare il layer da visualizzare all'interno del cannocchiale",
disableTips:"Fare clic per disabilitare lo strumento Scorrimento con dito",enableTips:"Fare clic per abilitare lo strumento Scorrimento con dito",defaultLayerHolder:"Fare clic per selezionare",selectLayers:"Seleziona layer",nItemsSelected:"layer selezionato/i",showList:"mostra elenco layer",hideList:"nascondi elenco layer",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Cursore temporale",enableTips:"Fare clic per visualizzare il cursore temporale.",disableTips:"Nessun layer abilitato per le variazioni temporali visibile.",
timeExtent:"Da ${FROMTIME} a ${ENDTIME}",layers:"Layer: ",speedLabel:"Velocit\u00e0 di riproduzione",liveData:"Dati in tempo reale",_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"Mappa d'insieme",_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Home",_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"Posizione",title:"Trova posizione personale",browserError:"Geolocalizzazione non supportata dal browser in uso.",failureFinding:"Impossibile trovare la posizione. Controllare il browser per verificare che la posizione sia condivisa.",
httpNotSupportError:"Questo widget \u00e8 disponibile solo quando l'accesso all'app viene eseguito tramite HTTPS in questo browser.",_localized:{}},"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Mostra o nascondi colonne",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Tabella attributi",_featureAction_ShowRelatedRecords:"Mostra record correlati",_featureAction_ViewInTable:"Visualizza nella tabella degli attributi",ok:"OK",cancel:"Annulla",
unsupportQueryWarning:"Il layer deve supportare la funzionalit\u00e0 delle query per essere visualizzato nel widget Tabella attributi. Accertarsi che la funzionalit\u00e0 delle query in questo servizio sia abilitata.",exportMessage:"Esportare i dati nel file CSV?",exportFiles:"Esporta in CSV",exportSelected:"Esporta selezionato in CSV",exportAll:"Esporta tutto in CSV",options:"Opzioni",zoomto:"Zoom a",highlight:"Evidenzia elementi grafici",selectAll:"Seleziona record in tutte le pagine",selectPage:"Seleziona record nella pagina corrente",
clearSelection:"Cancella selezione",filter:"Filtro",setFilterTip:"Impostare i filtri correttamente.",noFilterTip:"Se non si definisce nessuna espressione di filtro, questa attivit\u00e0 di interrogazione restituir\u00e0 tutte le feature presenti nell'origine dati specificata.",filterByExtent:"Filtro per estensione mappa",showSelectedRecords:"Mostra i record selezionati",showAllRecords:"Mostra tutti i record",showRelatedRecords:"Mostra record correlati",noRelatedRecords:"Nessun record correlato trovato",
highlightAllRecords:"Evidenzia tutti i record sulla mappa",attachmentColumn:"Foto e file",refresh:"Aggiorna",features:"feature",records:"dei record",selected:"selezionate",transparent:"Modalit\u00e0 trasparente",indicate:"Individua selezione",columns:"Mostra/nascondi colonne",selectionSymbol:"Simbolo di selezione",closeMessage:"Nascondi tabella (espanderla di nuovo dalla parte inferiore)",dataNotAvailable:"Dati non disponibili.\x3cbr\x3eFare clic su [Aggiorna] per riprovare.",openTableTip:"Apri tabella attributi",
closeTableTip:"Nascondi tabella attributi",sortAsc:"Ordinamento crescente",sortDes:"Ordinamento decrescente",statistics:"Statistiche",attachments:"Allegati",files:"file",keepRichTextLabel:"Mantieni Rich Text Format",whatsThis:"Guida rapida",richTextMessage:{explanatoryText:{line1:"${layerName} contiene i seguenti campi Rich Text Format: ",line2:" che potrebbe includere stili di formattazione del testo, come caratteri, colori o dimensione testo.",line3:'In caso di esportazione in CSV, gli stili di formattazione verranno mantenuti sotto forma di tag HTML. \u00c8 possibile scegliere di non mantenere i formati RTF deselezionando la casella "Mantieni Rich Text Format.'},
example:{label:"Ad esempio:",scenarios:{first:"viene esportato come il seguente testo per impostazione predefinita:",second:"e il seguente testo senza Rich Text Format:"}}},noTablesAvailable:"Nessuna tabella disponibile per la visualizzazione.",checkConfigutationToSelectLayers:"Accedere alla pagina delle impostazioni del widget per selezionare i layer.",checkLayerListToSelectLayers:"La Tabella attributi \u00e8 sincronizzata con i layer visibili nella mappa; \u00e8 possibile usare widget come Elenco layer per attivare/disattivare i layer.",
_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Cursore zoom",_localized:{}}});