//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Inklapbaar thema",_layout_default:"Standaardlay-out",_layout_layout1:"Lay-out 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"Controller van koptekst",signin:"Aanmelden",signout:"Meld u af",about:"Over",signInTo:"Meld u aan bij",cantSignOutTip:"Deze functie is niet beschikbaar in de voorbeeldmodus.",more:"meer",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"Schaalbalk",_localized:{}},
"esri/layers/vectorTiles/nls/common":{_localized:{}},"widgets/Search/nls/strings":{_widgetLabel:"Zoeken",searchResult:"Search Results",showAllResults:"Toon zoekresultaten voor ",showAll:"Toon zoekresultaten",more:"meer",untitled:"Naamloos",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Co\u00f6rdinaat",hintMessage:"Klik op de kaart om de co\u00f6rdinaten te krijgen",defaultLabel:"Standaard",realtimeLabel:"Beweeg de muis om de co\u00f6rdinaten te verkrijgen",computing:"Bezig met berekenen...",
latitudeLabel:"Breedtegraad",longitudeLabel:"Lengtegraad",loading:"laden...",enableClick:"Klik om, co\u00f6rdinaten te krijgen bij het klikken op de kaart, in te schakelen",disableClick:"Klik om, co\u00f6rdinaten te krijgen bij het klikken op de kaart, uit te schakelen",Default:"Standaard",Inches:"Inch",Foot:"Voet",Foot_US:"Voet_VS",Yards:"Yard",Miles:"Mijl",Nautical_Miles:"Zeemijl",Millimeters:"Millimeter",Centimeters:"Centimeter",Meter:"Meter",Kilometers:"Kilometer",Decimeters:"Decimeter",Decimal_Degrees:"Graden",
Degree_Minutes_Seconds:"Graden minuten seconden",MGRS:"MGRS",USNG:"USNG",_localized:{}},"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"Er moet ten minste \u00e9\u00e9n item geselecteerd worden.",multiSelectLabelText:"{num} item(s) geselecteerd",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"Swipe",swipeText:" Selecteer de la(a)g(en) waarop swipe moet worden toegepast",spyglassText:"Selecteer de laag die binnen de verrekijker moet verschijnen",disableTips:"Klik om de tool swipe uit te schakelen",
enableTips:"Klik om de tool swipe in te schakelen",defaultLayerHolder:"Klik om te selecteren",selectLayers:"Lagen selecteren",nItemsSelected:"la(a)g(en) geselecteerd",showList:"lijst met lagen weergeven",hideList:"lijst met lagen verbergen",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Time Slider",enableTips:"Klik hier om de tijdschuifregelaar weer te geven.",disableTips:"Er zijn geen lagen met tijdfunctionaliteit zichtbaar.",timeExtent:"${FROMTIME} naar ${ENDTIME}",layers:"Lagen: ",
speedLabel:"Playback speed",liveData:"Live gegevens",_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"Overzichtskaart",_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Home",_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"Mijn locatie",title:"Mijn locatie zoeken",browserError:"Geografische locatie wordt niet ondersteund door deze browser.",failureFinding:"Kan uw locatie niet vinden. Controleer uw browser om er zeker van te zijn dat uw locatie wordt gedeeld.",
httpNotSupportError:"Deze widget is alleen beschikbaar wanneer de app geopend wordt via HTTPS in deze browser.",_localized:{}},"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Kolommen weergeven of verbergen",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Attribuuttabel",_featureAction_ShowRelatedRecords:"Gerelateerde records weergeven",_featureAction_ViewInTable:"Bekijken in Attribuuttabel",ok:"OK",cancel:"Annuleren",unsupportQueryWarning:"De laag moet querybewerking ondersteunen voor weergave in de widget Attribuuttabel. Zorg ervoor dat de querybewerking in de service aan is.",
exportMessage:"Gegevens exporteren naar CSV-bestand?",exportFiles:"Exporteren naar CSV",exportSelected:"Selectie naar CSV exporteren",exportAll:"Alles naar CSV exporteren",options:"Opties",zoomto:"Zoomen naar",highlight:"Grafische elementen markeren",selectAll:"Records op alle pagina\u00b4s selecteren",selectPage:"Records op huidige pagina selecteren",clearSelection:"Selectie opheffen",filter:"Filter",setFilterTip:"Stel filters correct in.",noFilterTip:"Zonder filterexpressie zal deze querytaak alle functies in de opgegeven gegevensbron weergeven.",
filterByExtent:"Filteren op kaartextent",showSelectedRecords:"Geselecteerde records weergeven",showAllRecords:"Alle records weergeven",showRelatedRecords:"Gerelateerde records weergeven",noRelatedRecords:"Geen verwante records gevonden",highlightAllRecords:"Markeer alle records op de kaart",attachmentColumn:"Foto's en bestanden",refresh:"Vernieuwen",features:"objecten",records:"records",selected:"geselecteerd",transparent:"Transparante modus",indicate:"Selectie zoeken",columns:"Kolommen weergeven/verbergen",
selectionSymbol:"Selectiesymbool",closeMessage:"Tabel verbergen (opnieuw uitvouwen vanaf de onderkant)",dataNotAvailable:"Gegevens niet beschikbaar!\x3cbr\x3eKlik op de knop [Vernieuwen] om het nog eens te proberen.",openTableTip:"Attributentabel openen",closeTableTip:"Attributentabel verbergen",sortAsc:"Oplopend sorteren",sortDes:"Aflopend sorteren",statistics:"Statistieken",attachments:"Bijlagen",files:"bestanden",keepRichTextLabel:"Rich text-formaat behouden",whatsThis:"Wat is dit?",richTextMessage:{explanatoryText:{line1:"${layerName} bevat de volgende rich text-veld(en): ",
line2:" dat kan tekstopmaakstijlen omvatten, zoals lettertypen, kleuren of tekstformaten.",line3:'Bij export naar CSV worden de opmaakstijlen bewaard in de vorm van HTML-tags. U kunt ervoor kiezen om de rich-text-formaten niet te behouden door het vakje "Rich text-formaat behouden" uit te schakelen.'},example:{label:"Bijvoorbeeld:",scenarios:{first:"wordt standaard als de volgende tekst ge\u00ebxporteerd:",second:"en de volgende tekst zonder rich text-formaat:"}}},noTablesAvailable:"Geen tabellen beschikbaar om weer te geven.",
checkConfigutationToSelectLayers:"Ga naar de widgetinstellingenpagina voor het selecteren van lagen.",checkLayerListToSelectLayers:"Attribuuttabel is gesynchroniseerd met de zichtbare lagen in de tabel. U kunt widgets gebruiken als Lagenlijst om te schakelen tussen het aan- en uitzetten van lagen.",_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Zoomschuifregelaar",_localized:{}}});