//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Foldbart tema",_layout_default:"Standardlayout",_layout_layout1:"Layout 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"Header-controller",signin:"Sign in",signout:"Log ud",about:"Om",signInTo:"Log ind p\u00e5",cantSignOutTip:"Denne funktion er ikke relevant i forh\u00e5ndsvisningen.",more:"mere",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"M\u00e5lestok",_localized:{}},"esri/layers/vectorTiles/nls/common":{_localized:{}},
"widgets/Search/nls/strings":{_widgetLabel:"S\u00f8g",searchResult:"S\u00f8geresultater",showAllResults:"Vis s\u00f8geresultater for ",showAll:"Vis s\u00f8geresultater",more:"mere",untitled:"Untitled",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Koordinat",hintMessage:"Klik p\u00e5 kortet for at hente koordinater",defaultLabel:"Standard",realtimeLabel:"Flyt musen for at f\u00e5 koordinaterne",computing:"Behandler...",latitudeLabel:"Breddegrad",longitudeLabel:"L\u00e6ngdegrad",loading:"indl\u00e6ser...",
enableClick:"Klik for at aktivere klik p\u00e5 kortet for at f\u00e5 koordinater",disableClick:"Klik for at deaktivere klik p\u00e5 kortet for at f\u00e5 koordinater",Default:"Standard",Inches:"Inches",Foot:"Fod",Foot_US:"Feet_US",Yards:"Yards",Miles:"Miles",Nautical_Miles:"S\u00f8mil",Millimeters:"Millimeter",Centimeters:"Centimeter",Meter:"Meter",Kilometers:"Kilometer",Decimeters:"Decimeter",Decimal_Degrees:"Grader",Degree_Minutes_Seconds:"Grader Minutter Sekunder",MGRS:"MGRS",USNG:"USNG",_localized:{}},
"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"Du skal v\u00e6lge mindst \u00e9t element.",multiSelectLabelText:"{num} element(er) valgt",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"Swipe",swipeText:" V\u00e6lg det eller de lag, hvor du vil bruge swipe",spyglassText:"V\u00e6lg det lag, der skal vises i kikkerten",disableTips:"Klik for at deaktivere swipe-v\u00e6rkt\u00f8jet",enableTips:"Klik for at aktivere swipe-v\u00e6rkt\u00f8jet",defaultLayerHolder:"Klik for at v\u00e6lge",
selectLayers:"V\u00e6lg lag",nItemsSelected:"valgte lag",showList:"vis lagliste",hideList:"skjul lagliste",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Tidsskyder",enableTips:"Klik for at vise tidsskyderen.",disableTips:"Ingen tidsafh\u00e6ngige lag er synlige.",timeExtent:"${FROMTIME} til ${ENDTIME}",layers:"Lag: ",speedLabel:"Afspilningshastighed",liveData:"Live-data",_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"Oversigtskort",_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Hjem",
_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"Min position",title:"Find min placering",browserError:"Denne browser underst\u00f8tter ikke geoplaceringer.",failureFinding:"Din placering kan ikke findes. Tjek din browser for at sikre, at din placering deles.",httpNotSupportError:"Denne widget er kun tilg\u00e6ngelig, n\u00e5r app'en \u00e5bnes via HTTPS i denne browser.",_localized:{}},"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Vis eller skjul kolonner",
_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Attributtabel",_featureAction_ShowRelatedRecords:"Vis relaterede poster",_featureAction_ViewInTable:"Vis i attributtabel",ok:"OK",cancel:"Annuller",unsupportQueryWarning:"Laget skal underst\u00f8tte, at foresp\u00f8rgsler bliver vist i attributtabel-widget. Kontroll\u00e9r, at foresp\u00f8rgselsfunktionen er aktiveret i tjenesten.",exportMessage:"Skal dataene eksporteres til en CSV-fil?",exportFiles:"Eksport\u00e9r til CSV",exportSelected:"Eksport\u00e9r markeringen til CSV",
exportAll:"Eksport\u00e9r alt til CSV",options:"Indstillinger",zoomto:"Zoom til",highlight:"Fremh\u00e6v grafik",selectAll:"Mark\u00e9r poster p\u00e5 alle sider",selectPage:"Mark\u00e9r poster p\u00e5 den aktuelle side",clearSelection:"Clear selection",filter:"Filtr\u00e9r",setFilterTip:"Angiv filteret korrekt.",noFilterTip:"Hvis der ikke defineres nogen filterudtryk, viser denne foresp\u00f8rgsel alle objekter i den angivne datakilde.",filterByExtent:"Filtr\u00e9r efter kortudstr\u00e6kning",showSelectedRecords:"Vis valgte poster",
showAllRecords:"Vis alle poster",showRelatedRecords:"Vis relaterede poster",noRelatedRecords:"Ingen relaterede poster fundet",highlightAllRecords:"Fremh\u00e6v alle poster p\u00e5 kortet",attachmentColumn:"Fotos og filer",refresh:"Opdat\u00e9r",features:"objekter",records:"poster",selected:"valgt",transparent:"Transparent tilstand",indicate:"Valg af landeindstillinger",columns:"Vis/Skjul kolonner",selectionSymbol:"Markeringssymbol",closeMessage:"Skjul tabel (vis den igen nedefra)",dataNotAvailable:"Dataene er ikke tilg\u00e6ngelige!\x3cbr\x3eKlik p\u00e5 knappen [Opdater] for at pr\u00f8ve igen",
openTableTip:"\u00c5bn attributtabel",closeTableTip:"Skjul attributtabel",sortAsc:"Sort\u00e9r stigende",sortDes:"Sort\u00e9r faldende",statistics:"Statistik",attachments:"Vedh\u00e6ftninger",files:"filer",keepRichTextLabel:"Behold rich text-format",whatsThis:"Hvad er dette?",richTextMessage:{explanatoryText:{line1:"${layerName} indeholder f\u00f8lgende rich text-felt(er): ",line2:" det kan omfatte teksttypografier, f.eks. skrifttyper, farver eller tekstst\u00f8rrelser.",line3:'N\u00e5r de eksporteres til CSV, bevares typografierne i form af HTML-tags. Du kan v\u00e6lge ikke at beholde rich text-formaterne ved at fjerne markeringen i feltet "Behold rich text-format".'},
example:{label:"For eksempel:",scenarios:{first:"bliver eksporteret som f\u00f8lgende tekst som standard:",second:"og f\u00f8lgende tekst uden rich text-format:"}}},noTablesAvailable:"Der er ingen tabeller at vise.",checkConfigutationToSelectLayers:"G\u00e5 til siden for widget-indstillinger for at v\u00e6lge lag.",checkLayerListToSelectLayers:"Attribut-tabellen er synkroniseret med de synlige lag i kortet. Du kan bruge widgets som Lagliste til at vise/skjule lag.",_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Zoom-skyder",
_localized:{}}});