//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Tema Dobr\u00e1vel",_layout_default:"Layout padr\u00e3o",_layout_layout1:"Layout 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"Controlador do Cabe\u00e7alho",signin:"Entrar",signout:"Sair",about:"Sobre",signInTo:"Entrar no",cantSignOutTip:"Esta fun\u00e7\u00e3o \u00e9 N/A no modo de visualiza\u00e7\u00e3o.",more:"mais",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"Barra de Escala",
_localized:{}},"esri/layers/vectorTiles/nls/common":{_localized:{}},"widgets/Search/nls/strings":{_widgetLabel:"Pesquisar",searchResult:"Resultado de pesquisa",showAllResults:"Mostrar resultados da pesquisa para ",showAll:"Mostrar resultados da pesquisa",more:"mais",untitled:"Sem t\u00edtulo",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Coordenada",hintMessage:"Clique no mapa para obter coordenadas",defaultLabel:"Padr\u00e3o",realtimeLabel:"Mover mouse para obter coordenadas",computing:"Calculando...",
latitudeLabel:"Latitude",longitudeLabel:"Longitude",loading:"carregando...",enableClick:"Clique para habilitar o clique no mapa para obter coordenadas",disableClick:"Clique para desabilitar o clique no mapa para obter coordenadas",Default:"Padr\u00e3o",Inches:"Polegadas",Foot:"P\u00e9s",Foot_US:"Feet_US",Yards:"Jardas",Miles:"Milhas",Nautical_Miles:"Milhas n\u00e1uticas",Millimeters:"Mil\u00edmetros",Centimeters:"Cent\u00edmetros",Meter:"Metros",Kilometers:"Quil\u00f4metros",Decimeters:"Dec\u00edmetros",
Decimal_Degrees:"Graus",Degree_Minutes_Seconds:"Graus minutos segundos",MGRS:"MGRS",USNG:"USNG",_localized:{}},"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"Ao menos um item deve ser selecionado.",multiSelectLabelText:"{num} item(ns) selecionado(s)",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"Oscilar",swipeText:" Selecione as camadas que deseja oscilar",spyglassText:"Selecione a camada para aparecer na luneta",disableTips:"Clique para desativar a ferramenta de oscila\u00e7\u00e3o",
enableTips:"Clique para ativar a ferramenta de oscila\u00e7\u00e3o",defaultLayerHolder:"Clique para selecionar",selectLayers:"Selecionar camadas",nItemsSelected:"camadas selecionadas",showList:"mostrar lista de camadas",hideList:"ocultar lista de camadas",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Controle Deslizante de Tempo",enableTips:"Clique para exibir o controle deslizante de tempo.",disableTips:"Nenhuma camada de indica\u00e7\u00e3o de tempo est\u00e1 vis\u00edvel.",timeExtent:"${FROMTIME} para ${ENDTIME}",
layers:"Camadas: ",speedLabel:"Velocidade de reprodu\u00e7\u00e3o",liveData:"Dados Atuais",_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"Mapa de Vis\u00e3o Geral",_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"P\u00e1gina Inicial",_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"Meu Local",title:"Encontrar meu local",browserError:"A geolocaliza\u00e7\u00e3o n\u00e3o \u00e9 suportada por este navegador.",failureFinding:"N\u00e3o \u00e9 poss\u00edvel encontrar seu local. Verifique seu navegador para garantir que seu local est\u00e1 compartilhado.",
httpNotSupportError:"Este widget est\u00e1 dispon\u00edvel somente quando o aplicativo for acessado via HTTPS neste navegador.",_localized:{}},"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Mostrar ou ocultar colunas",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Tabela de Atributos",_featureAction_ShowRelatedRecords:"Mostrar registros relacionados",_featureAction_ViewInTable:"Visualizar na Tabela de Atributos",ok:"OK",cancel:"Cancelar",
unsupportQueryWarning:"A camada precisa suportar a opera\u00e7\u00e3o de consulta para aparecer no widget da Tabela de Atributo. Certifique-se que o recurso de consulta no servi\u00e7o est\u00e1 ativado.",exportMessage:"Exportar dados para arquivo CSV?",exportFiles:"Exportar para CSV",exportSelected:"Exportar selecionado para CSV",exportAll:"Exportar todos para CSV",options:"Op\u00e7\u00f5es",zoomto:"Zoom para",highlight:"Destacar gr\u00e1ficos",selectAll:"Selecionar registros em todas as p\u00e1ginas",
selectPage:"Selecionar registros na p\u00e1gina atual",clearSelection:"Limpar sele\u00e7\u00e3o",filter:"Filtro",setFilterTip:"Configure o filtro corretamente.",noFilterTip:"Sem express\u00f5es de filtro definidas, esta tarefa de consulta listar\u00e1 todas as fei\u00e7\u00f5es na fonte de dados especificada.",filterByExtent:"Filtrar por extens\u00e3o de mapa",showSelectedRecords:"Mostrar registros selecionados",showAllRecords:"Mostrar todos os registros",showRelatedRecords:"Mostrar registros relacionados",
noRelatedRecords:"Nenhum registro relacionado encontrado",highlightAllRecords:"Destaque todos os registros no mapa",attachmentColumn:"Fotos e arquivos",refresh:"Atualizar",features:"recursos",records:"registros",selected:"selecionado",transparent:"Modo transparente",indicate:"Sele\u00e7\u00e3o de local",columns:"Mostrar/Ocultar colunas",selectionSymbol:"S\u00edmbolo de sele\u00e7\u00e3o",closeMessage:"Ocultar tabela (expanda novamente da parte inferior)",dataNotAvailable:"Dados n\u00e3o dispon\u00edveis!\x3cbr\x3eClique no bot\u00e3o [Atualizar] para tentar noamente.",
openTableTip:"Abrir Tabela de Atributo",closeTableTip:"Ocultar Tabela de Atributos",sortAsc:"Ordem crescente",sortDes:"Ordem decrescente",statistics:"Estat\u00edstica",attachments:"Anexos",files:"arquivos",keepRichTextLabel:"Manter formato rich text",whatsThis:"O que \u00e9 Isto?",richTextMessage:{explanatoryText:{line1:"${layerName} cont\u00e9m os seguintes campos de rich text: ",line2:" Isto pode incluir estilos da formata\u00e7\u00e3o de texto, como fontes, cores ou tamanhos de texto.",line3:'Quando exportados para CSV, os estilos de formata\u00e7\u00e3o ser\u00e3o preservados na forma de tags da HTML. Voc\u00ea pode optar por n\u00e3o manter os formatos rich text, desmarcando a caixa "Manter formato rich text".'},
example:{label:"Por exemplo:",scenarios:{first:"ser\u00e1 exportado como o seguinte texto por padr\u00e3o:",second:"e o seguinte texto sem formato rich text:"}}},noTablesAvailable:"Nenhuma tabela dispon\u00edvel para exibir.",checkConfigutationToSelectLayers:"V\u00e1 at\u00e9 a p\u00e1gina de configura\u00e7\u00f5es do widget para selecionar camadas.",checkLayerListToSelectLayers:"A Tabela de Atributo \u00e9 sincronizada com as camadas vis\u00edveis no mapa, voc\u00ea pode utilizar o widget como Lista de Camada para ativar/desativar as camadas.",
_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Controle Deslizante de Zoom",_localized:{}}});