//>>built
define({"themes/FoldableTheme/nls/strings":{_themeLabel:"Foldable Theme",_layout_default:"Default layout",_layout_layout1:"Layout 1",_localized:{}},"themes/FoldableTheme/widgets/HeaderController/nls/strings":{_widgetLabel:"Header Controller",signin:"Sign in",signout:"Sign out",about:"About",signInTo:"Sign in to",cantSignOutTip:"This function is N/A in preview mode.",more:"more",_localized:{}},"widgets/Scalebar/nls/strings":{_widgetLabel:"Scalebar",_localized:{}},"esri/layers/vectorTiles/nls/common":{_localized:{}},
"widgets/Search/nls/strings":{_widgetLabel:"Search",searchResult:"Search result",showAllResults:"Show search results for ",showAll:"Show search results",more:"more",untitled:"Untitled",_localized:{}},"widgets/Coordinate/nls/strings":{_widgetLabel:"Coordinate",hintMessage:"Click the map to get coordinates",defaultLabel:"Default",realtimeLabel:"Move mouse to get coordinates",computing:"Computing...",latitudeLabel:"Latitude",longitudeLabel:"Longitude",loading:"loading...",enableClick:"Click to enable clicking map to get coordinates",
disableClick:"Click to disable clicking map to get coordinates",Default:"Default",Inches:"Inches",Foot:"Feet",Foot_US:"Feet_US",Yards:"Yards",Miles:"Miles",Nautical_Miles:"Nautical miles",Millimeters:"Millimeters",Centimeters:"Centimeters",Meter:"Meters",Kilometers:"Kilometers",Decimeters:"Decimeters",Decimal_Degrees:"Degrees",Degree_Minutes_Seconds:"Degrees minutes seconds",MGRS:"MGRS",USNG:"USNG",_localized:{}},"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"At least one item must be selected.",
multiSelectLabelText:"{num} item(s) selected",_localized:{}},"widgets/Swipe/nls/strings":{_widgetLabel:"Swipe",swipeText:" Select the layer(s) you want to swipe",spyglassText:"Select the layer to appear within the spyglass",disableTips:"Click to disable the swipe tool",enableTips:"Click to enable the swipe tool",defaultLayerHolder:"Click to select",selectLayers:"Select layers",nItemsSelected:"layer(s) selected",showList:"show layers list",hideList:"hide layers list",_localized:{}},"widgets/TimeSlider/nls/strings":{_widgetLabel:"Time Slider",
enableTips:"Click to display the time slider.",disableTips:"No time-aware layers are visible.",timeExtent:"${FROMTIME} to ${ENDTIME}",layers:"Layers: ",speedLabel:"Playback speed",liveData:"Live data",_localized:{}},"widgets/OverviewMap/nls/strings":{_widgetLabel:"Overview Map",_localized:{}},"widgets/HomeButton/nls/strings":{_widgetLabel:"Home",_localized:{}},"widgets/MyLocation/nls/strings":{_widgetLabel:"My Location",title:"Find my location",browserError:"Geolocation is not supported by this browser.",
failureFinding:"Can not find your location. Please check your browser to ensure that your location is shared.",httpNotSupportError:"This widget is available only when the app is accessed through HTTPS in this browser.",_localized:{}},"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Show or hide columns",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Attribute Table",_featureAction_ShowRelatedRecords:"Show related records",_featureAction_ViewInTable:"View in Attribute Table",
ok:"OK",cancel:"Cancel",unsupportQueryWarning:"The layer needs to support query operation to display in Attribute Table widget. Make sure the query capability in the service is turned on.",exportMessage:"Export data to CSV file?",exportFiles:"Export to CSV",exportSelected:"Export selected to CSV",exportAll:"Export all to CSV",options:"Options",zoomto:"Zoom to",highlight:"Highlight graphics",selectAll:"Select records in all pages",selectPage:"Select records in current page",clearSelection:"Clear selection",
filter:"Filter",setFilterTip:"Please set filters correctly.",noFilterTip:"Without filter expressions defined, this query task will list all features in the specified data source.",filterByExtent:"Filter by map extent",showSelectedRecords:"Show selected records",showAllRecords:"Show all records",showRelatedRecords:"Show related records",noRelatedRecords:"No related records found",highlightAllRecords:"Highlight all records on map",attachmentColumn:"Photos and files",refresh:"Refresh",features:"features",
records:"records",selected:"selected",transparent:"Transparent mode",indicate:"Locate selection",columns:"Show/Hide columns",selectionSymbol:"Selection symbol",closeMessage:"Hide table (expand it again from the bottom)",dataNotAvailable:"Data not available!\x3cbr\x3eClick [Refresh] button to try again.",openTableTip:"Open Attribute Table",closeTableTip:"Hide Attribute Table",sortAsc:"Sort ascending",sortDes:"Sort descending",statistics:"Statistics",attachments:"Attachments",files:"files",keepRichTextLabel:"Keep rich text format",
whatsThis:"What's this?",richTextMessage:{explanatoryText:{line1:"${layerName} contains the following rich text field(s): ",line2:" that may include text formatting styles, such as fonts, colors or text sizes.",line3:'When exported to CSV, the formatting styles will be preserved in the form of HTML tags. You can choose not to keep the rich text formats by unchecking the "Keep rich text format" box.'},example:{label:"For example:",scenarios:{first:"will be exported as the following text by default:",
second:"and the following text without rich text format:"}}},noTablesAvailable:"No tables available to display.",checkConfigutationToSelectLayers:"Please go to widget settings page to select layers.",checkLayerListToSelectLayers:"Attribute Table is synchronized with visible layers in the map,  you can use widget such as Layer List to toggle on/off layers.",_localized:{}},"widgets/ZoomSlider/nls/strings":{_widgetLabel:"Zoom Slider",_localized:{}}});