//>>built
define("dojo/_base/declare dojo/mouse dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable jimu/LayerInfos/LayerInfos jimu/dijit/LoadingIndicator dojo/_base/lang dojo/_base/html dojo/on dojo/_base/array dojo/promise/all dijit/popup dijit/TooltipDialog ./EditFields ../utils dijit/form/NumberSpinner dijit/form/RadioButton".split(" "),function(r,n,t,u,p,v,w,g,k,l,h,x,q,y,z,m){return r([u,t],{baseClass:"jimu-widget-edit-setting",_jimuLayerInfos:null,_layersTable:null,_tablesTable:null,
_editableLayerInfos:null,_editableTableInfos:null,_tooltipTimeout:1E3,startup:function(){this.inherited(arguments);v.getInstance(this.map,this.map.itemInfo).then(g.hitch(this,function(a){this._jimuLayerInfos=a;this._init();this.setConfig()}))},_init:function(){this._initToolbar();this._initCustomSettingRadio();this._initLayersTable();this._initTablesTable()},_initToolbar:function(){this.useFilterEdit.setValue(this.config.editor.useFilterEdit);this.toolbarVisible.setValue(this.config.editor.toolbarVisible);
this.enableUndoRedo.setValue(this.config.editor.enableUndoRedo);this.mergeVisible.setValue(this.config.editor.toolbarOptions.mergeVisible);this.cutVisible.setValue(this.config.editor.toolbarOptions.cutVisible);this.reshapeVisible.setValue(this.config.editor.toolbarOptions.reshapeVisible);this.usingSaveButton.setValue(this.config.editor.usingSaveButton);this.autoApplyEditWhenGeometryIsMoved.setValue(this.config.editor.autoApplyEditWhenGeometryIsMoved);this.snappingTolerance.set("value",void 0===this.config.editor.snappingTolerance?
15:this.config.editor.snappingTolerance);this.popupTolerance.set("value",void 0===this.config.editor.popupTolerance?5:this.config.editor.popupTolerance);this.stickyMoveTolerance.set("value",void 0===this.config.editor.stickyMoveTolerance?0:this.config.editor.stickyMoveTolerance)},_initCustomSettingRadio:function(){this.config.editor.honorSettingOfWebmap?this.webmapRadio.set("checked",!0):this.config.editor.layerInfos&&0===this.config.editor.layerInfos.length&&this.config.editor.tableInfos&&0===this.config.editor.tableInfos.length?
this.webmapRadio.set("checked",!0):this.customRadio.set("checked",!0);this._controlCustomSettingRadio();this.own(l(this.webmapRadio,"click",g.hitch(this,this._onRadioClicke)));this.own(l(this.customRadio,"click",g.hitch(this,this._onRadioClicke)));this._initTooltipDialog()},_initTooltipDialog:function(){var a=k.create("div",{innerHTML:'\x3cdiv class\x3d"title"\x3e'+this.nls.honorTheWebMapSettingTip1+'\x3c/div\x3e\x3cdiv class\x3d"item new-selection-item"\x3e'+("- "+this.nls.honorTheWebMapSettingTip2)+
'\x3c/div\x3e\x3cdiv class\x3d"item add-selection-item"\x3e'+("- "+this.nls.honorTheWebMapSettingTip3)+'\x3c/div\x3e\x3cdiv class\x3d"item remove-selection-item"\x3e'+("- "+this.nls.honorTheWebMapSettingTip4)+"\x3c/div\x3e","class":"dialog-content"});this.tooltipDialog1=new y({content:a});k.addClass(this.tooltipDialog1.domNode,"jimu-multiple-layers-featureset-chooser-tooltipdialog");this.own(l(this.webmapRadioBoxDom,"mousemove",g.hitch(this,function(a){this._tooltipDialogClientX1=a.clientX})));this.own(l(this.webmapRadioBoxDom,
n.enter,g.hitch(this,function(){clearTimeout(this._tooltipDialogTimeoutId1);this._tooltipDialogTimeoutId1=-1;this._tooltipDialogTimeoutId1=setTimeout(g.hitch(this,function(){this.tooltipDialog1&&(q.open({parent:this.getParent(),popup:this.tooltipDialog1,around:this.webmapRadioBoxDom,position:["below"]}),0<=this._tooltipDialogClientX1&&(this.tooltipDialog1.domNode.parentNode.style.left=this._tooltipDialogClientX1+"px"))}),this._tooltipTimeout)})));this.own(l(this.webmapRadioBoxDom,n.leave,g.hitch(this,
function(){clearTimeout(this._tooltipDialogTimeoutId1);this._tooltipDialogTimeoutId1=-1;this._hideTooltipDialog(this.tooltipDialog1)})))},_hideTooltipDialog:function(a){a&&q.close(a)},_initLayersTable:function(){this._layersTable=new p({fields:[{name:"edit",title:this.nls.edit,type:"checkbox","class":"editable"},{name:"label",title:this.nls.label,type:"text"},{name:"allowCreateCheckBox",title:window.jimuNls.common.add,type:"checkbox","class":"update",width:"100px"},{name:"allowDeleteCheckBox",title:window.jimuNls.common.deleteText,
type:"checkbox","class":"update",width:"100px"},{name:"allowGeometryUpdateCheckBox",title:window.jimuNls.common.updateGeometry,type:"checkbox","class":"update",width:"160px"},{name:"actions",title:this.nls.fields,type:"actions","class":"edit-fields",actions:["edit"]}],selectable:!1});this._layersTable.placeAt(this.layerInfosTable);this._layersTable.startup();this.own(l(this._layersTable,"actions-edit",g.hitch(this,this._onEditFieldInfoClick,this._layersTable)))},_initTablesTable:function(){this._tablesTable=
new p({fields:[{name:"edit",title:this.nls.edit,type:"checkbox","class":"editable"},{name:"label",title:window.jimuNls.common.table,type:"text"},{name:"allowCreateCheckBox",title:window.jimuNls.common.add,type:"checkbox","class":"update",width:"100px"},{name:"allowDeleteCheckBox",title:window.jimuNls.common.deleteText,type:"checkbox","class":"update",width:"100px"},{name:"placeholder",title:"",type:"text","class":"update",width:"160px"},{name:"actions",title:this.nls.fields,type:"actions","class":"edit-fields",
actions:["edit"]}],selectable:!1});this._tablesTable.placeAt(this.tableInfosTable);this._tablesTable.startup();this.own(l(this._tablesTable,"actions-edit",g.hitch(this,this._onEditFieldInfoClick,this._tablesTable)))},setConfig:function(){this._editableLayerInfos=this._getEditableLayerInfos();this._setTable(this._editableLayerInfos,this._layersTable);var a=(new w({hidden:!1})).placeAt(this.tableInfosLoading);this._getEditableTableInfos().then(g.hitch(this,function(b){a.destroy();this._editableTableInfos=
b;0<this._editableTableInfos.length&&(this._setTable(b,this._tablesTable),k.setStyle(this.tableInfosTable,"display","block"))}))},_getEditableTableInfos:function(){var a=[],b=[],c=[],d=this._jimuLayerInfos.getTableInfoArray(),e=[];h.forEach(this._editableLayerInfos,function(a){(a=this._jimuLayerInfos._findTopLayerInfoById(a.featureLayer.id))&&c.push(a)},this);h.forEach(c.concat(d),function(c){a.push(c.getRelatedTableInfoArray())},this);return x(a).then(g.hitch(this,function(a){h.forEach(a,function(a){e=
e.concat(a)},this);h.forEach(d,function(a){var c=a.layerObject,d=a.getCapabilitiesOfWebMap(),f=h.some(e,function(c){return a.id===c.id},this),d=d&&-1===d.toLowerCase().indexOf("editing")?!1:!0;"Table"===c.type&&c.url&&c.isEditable&&c.isEditable()&&d&&f&&((f=this._getLayerInfoFromConfiguration(c))||(f=this._getDefaultLayerInfo(c)),b.push(f))},this);return b}))},_getEditableLayerInfos:function(){for(var a=[],b=this.map.graphicsLayerIds.length-1;0<=b;b--){var c=this.map.getLayer(this.map.graphicsLayerIds[b]);
if("Feature Layer"===c.type&&c.url&&c.isEditable&&c.isEditable()){var d=this._getLayerInfoFromConfiguration(c);d||(d=this._getDefaultLayerInfo(c));a.push(d)}}return a},_getLayerInfoFromConfiguration:function(a){var b=null,c=this.config.editor.layerInfos?this.config.editor.layerInfos:[];if((c=c.concat(this.config.editor.tableInfos?this.config.editor.tableInfos:[]))&&0<c.length){for(var d=0;d<c.length;d++)if(c[d].featureLayer&&c[d].featureLayer.id===a.id){b=c[d];break}b&&(b.fieldInfos=this._getSimpleFieldInfos(a,
b),b._editFlag=!0)}return b},_getDefaultLayerInfo:function(a){var b=this.config.editor.layerInfos&&this.config.editor.tableInfos?this.config.editor.layerInfos.concat(this.config.editor.tableInfos):null;return{featureLayer:{id:a.id},disableGeometryUpdate:!1,allowCreate:!0,allowDelete:!0,fieldInfos:this._getSimpleFieldInfos(a),_editFlag:b&&0===b.length?!0:!1}},_setTable:function(a,b){h.forEach(a,function(a){var c=this._jimuLayerInfos.getLayerOrTableInfoById(a.featureLayer.id),e=m.getEditCapabilities(c.layerObject);
b.addRow({label:c.title,edit:a._editFlag,allowCreateCheckBox:e.canCreate?a.allowCreate:null,allowDeleteCheckBox:e.canDelete?a.allowDelete:null,allowGeometryUpdateCheckBox:e.canUpdateGeometry?!a.disableGeometryUpdate:null}).tr._layerInfo=a},this)},_getDefaultSimpleFieldInfos:function(a){for(var b=[],c,d,e=0;e<a.fields.length;e++)c=a.fields[e].editable?!0:null,d="globalid"!==a.fields[e].name.toLowerCase()&&a.fields[e].name!==a.objectIdField||a.fields[e].editable?!0:!1,b.push({fieldName:a.fields[e].name,
label:a.fields[e].alias||a.fields[e].name,isEditable:c,visible:d||c?!0:!1});return b},_getWebmapSimpleFieldInfos:function(a){var b,c,d=[],e=m.getFieldInfosFromWebmap(a.id,this._jimuLayerInfos);e?(h.forEach(e,function(e){m.ignoreCaseToGetFieldKey(a,e.fieldName)&&(b=e.isEditable,c=e.visible,d.push({fieldName:e.fieldName,label:e.label,isEditable:b,visible:c||b?!0:!1}))}),0===d.length&&(d=null)):d=null;return d},_getSimpleFieldInfos:function(a,b){var c,d=[],e=this._getDefaultSimpleFieldInfos(a),f=this._getWebmapSimpleFieldInfos(a);
c=f?f:e;b&&b.fieldInfos?(h.forEach(b.fieldInfos,function(a){if(void 0===a.visible)if(f)for(var b=0;b<f.length;b++)a.fieldName===f[b].fieldName&&(a.visible=f[b].visible||f[b].isEditable);else a.visible=!0;for(b=0;b<c.length;b++)if(a.fieldName===c[b].fieldName){d.push(a);c[b]._exit=!0;break}}),h.forEach(c,function(a){a._exit||d.push(a)})):d=c;return d},_onEditFieldInfoClick:function(a,b){(a=a.getRowData(b))&&a.edit&&(new z({nls:this.nls,_layerInfo:b._layerInfo})).popupEditPage()},_onToolbarSelected:function(){this.toolbarVisible.checked?
(k.removeClass(this.toolbarOptionsTr,"disable"),k.setStyle(this.toolbarOptionsCoverage,"display","none")):(k.addClass(this.toolbarOptionsTr,"disable"),k.setStyle(this.toolbarOptionsCoverage,"display","block"))},_resetToolbarConfig:function(){this.config.editor.useFilterEdit=this.useFilterEdit.checked;this.config.editor.toolbarVisible=this.toolbarVisible.checked;this.config.editor.enableUndoRedo=this.enableUndoRedo.checked;this.config.editor.toolbarOptions.mergeVisible=this.mergeVisible.checked;this.config.editor.toolbarOptions.cutVisible=
this.cutVisible.checked;this.config.editor.toolbarOptions.reshapeVisible=this.reshapeVisible.checked;this.config.editor.usingSaveButton=this.usingSaveButton.checked;this.config.editor.autoApplyEditWhenGeometryIsMoved=this.autoApplyEditWhenGeometryIsMoved.checked;this.config.editor.snappingTolerance=this.snappingTolerance.value;this.config.editor.popupTolerance=this.popupTolerance.value;this.config.editor.stickyMoveTolerance=this.stickyMoveTolerance.value},_resetCustomSettingConfig:function(){this.config.editor.honorSettingOfWebmap=
this.webmapRadio.get("checked")?!0:!1},_getCheckedLayerOrTableInfos:function(a,b){var c=[],d=b.getData();h.forEach(a,function(a,b){a._editFlag=d[b].edit;null!==d[b].allowCreateCheckBox&&(a.allowCreate=d[b].allowCreateCheckBox);null!==d[b].allowDeleteCheckBox&&(a.allowDelete=d[b].allowDeleteCheckBox);null!==d[b].allowGeometryUpdateCheckBox&&(a.disableGeometryUpdate=!d[b].allowGeometryUpdateCheckBox);a._editFlag&&(delete a._editFlag,c.push(a))});return c},getConfig:function(){this._resetToolbarConfig();
this._resetCustomSettingConfig();var a=this._getCheckedLayerOrTableInfos(this._editableLayerInfos,this._layersTable);0===a.length?delete this.config.editor.layerInfos:this.config.editor.layerInfos=a;a=this._getCheckedLayerOrTableInfos(this._editableTableInfos,this._tablesTable);0===a.length?delete this.config.editor.tableInfos:this.config.editor.tableInfos=a;return this.config},_controlCustomSettingRadio:function(){this.webmapRadio.get("checked")?k.addClass(this.layersSettingPart,"disable"):this.customRadio.get("checked")&&
k.removeClass(this.layersSettingPart,"disable")},_onRadioClicke:function(){this._controlCustomSettingRadio()}})});